export const WORDS = [
  { t: "palimpsest", p: "PAL-imp-sest", g: "a surface written over so the older writing still shows" },
  { t: "apophasis", p: "uh-POF-uh-sis", g: "mentioning something by saying you will not mention it" },
  { t: "quiddity", p: "KWID-ih-tee", g: "the essential what-ness of a thing" },
  { t: "haecceity", p: "hek-SEE-ih-tee", g: "the this-ness of one particular thing" },
  { t: "liminality", p: "lim-ih-NAL-ih-tee", g: "the state of being on a threshold" },
  { t: "chthonic", p: "THON-ik", g: "of the underworld; belonging beneath the earth" },
  { t: "numinous", p: "NOO-min-us", g: "filled with a sense of the sacred" },
  { t: "soteriology", p: "so-teer-ee-OL-uh-jee", g: "the study of what it means to be saved" },
  { t: "eschaton", p: "ES-kuh-ton", g: "the last thing; an end of history" },
  { t: "praxis", p: "PRAK-sis", g: "practice; theory carried out in action" },
  { t: "anagoge", p: "an-uh-GOH-jee", g: "a reading that lifts a text toward a higher sense" },
  { t: "catabasis", p: "kuh-TAB-uh-sis", g: "a descent, especially into the underworld" },
  { t: "peripeteia", p: "pehr-ih-puh-TEE-uh", g: "a sudden reversal of fortune" },
  { t: "aleatory", p: "AY-lee-uh-tor-ee", g: "dependent on chance" },
  { t: "agon", p: "AH-gohn", g: "a contest or structured struggle" },
  { t: "deixis", p: "DYKE-sis", g: "pointing at the here and now of speech" },
  { t: "colophon", p: "KOL-uh-fon", g: "a short note at the end of a book" },
  { t: "interstice", p: "in-TUR-stiss", g: "a small gap between things" },
  { t: "dialectic", p: "dye-uh-LEK-tik", g: "argument that moves by opposing claims" },
  { t: "immanence", p: "IM-uh-nunce", g: "being present within, not beyond" },
  { t: "transcendence", p: "tran-SEN-dunce", g: "going beyond ordinary limits" },
  { t: "eidolon", p: "eye-DOH-lon", g: "an image, phantom, or unsubstantial form" },
  { t: "simulacrum", p: "sim-yuh-LAY-krum", g: "a copy that stands in for the original" },
  { t: "mimesis", p: "mih-MEE-sis", g: "imitation; representation of the real" },
  { t: "semiosis", p: "see-mee-OH-sis", g: "the process by which signs make meaning" },
  { t: "indexical", p: "in-DEX-ih-kul", g: "a sign that points because it was there" },
  { t: "iconicity", p: "eye-kuh-NISS-ih-tee", g: "meaning that comes from resemblance" },
  { t: "symbolon", p: "SIM-buh-lon", g: "a token meant to be matched with its other half" },
  { t: "prosody", p: "PROSS-uh-dee", g: "the rhythm and sound pattern of speech" },
  { t: "caesura", p: "sih-ZYOOR-uh", g: "a pause in the middle of a line" },
  { t: "kenosis", p: "keh-NO-sis", g: "an emptying out of the self" },
  { t: "askesis", p: "uh-SKEE-sis", g: "discipline practiced as training" },
  { t: "thnetos", p: "THNET-oss", g: "mortal; liable to die" },
  { t: "anabasis", p: "uh-NAB-uh-sis", g: "a march up-country; an ascent" },
  { t: "topos", p: "TOH-poss", g: "a commonplace; a conventional theme" },
  { t: "genius loci", p: "JEE-nee-us LOH-sye", g: "the spirit or character of a place" },
  { t: "parataxis", p: "par-uh-TAK-sis", g: "placing clauses side by side without joining words" },
  { t: "hypotaxis", p: "hye-poh-TAK-sis", g: "subordinating one clause to another" },
  { t: "aporia", p: "uh-POR-ee-uh", g: "a productive puzzlement; being stuck in thought" },
  { t: "catachresis", p: "kat-uh-KREE-sis", g: "a strained or mixed figure of speech" },
  { t: "enargia", p: "en-AR-jee-uh", g: "vivid description that makes a scene present" },
  { t: "ekphrasis", p: "EK-fruh-sis", g: "speech that describes a work of art" },
  { t: "prosopopoeia", p: "pruh-so-puh-PEE-uh", g: "giving a voice to something that cannot speak" },
  { t: "chronotope", p: "KRON-uh-tope", g: "time and place fused as one setting" },
  { t: "heterotopia", p: "het-uh-roh-TOH-pee-uh", g: "a real place that works as another world inside the world" },
  { t: "limen", p: "LYE-men", g: "a threshold; the edge of crossing" },
  { t: "vestige", p: "VESS-tij", g: "a remaining trace of something gone" },
  { t: "palinode", p: "PAL-ih-node", g: "a poem or statement that takes back an earlier one" },
  { t: "recension", p: "rih-SEN-shun", g: "a distinct edited version of a text" },
  { t: "stela", p: "STEE-luh", g: "an upright stone marked with a name or record" },
  { t: "skull", p: "skul", g: "the mark that says you chose the fight and will pay the tax" },
  { t: "protect item", p: "pruh-TEKT EYE-tem", g: "the prayer that keeps one piece when the rest is the ditch" },
  { t: "freeze", p: "freez", g: "ice that holds a step so the spec is not a flex" },
  { t: "immunity", p: "ih-MYOO-nih-tee", g: "the ticks after a thaw when a spec is a donation" },
  { t: "pile", p: "pyl", g: "everyone hitting the same body in multi; you are it or you leave" },
  { t: "PJ", p: "pee-jay", g: "player-kill interrupt; the timer that says whose fight it is" },
  { t: "spec", p: "spek", g: "special attack; a bar you spend, not a personality" },
  { t: "eat cycle", p: "eet SY-kul", g: "food, brew, karambwan as one decision, not a flex" },
  { t: "risk", p: "risk", g: "the gold you will not tilt over; gear lives under that number" },
  { t: "wildy", p: "WILL-dee", g: "the ditch and everything north of it; official rules still win" },
  { t: "multi", p: "MUL-tee", g: "a tile where one target is a pile and a solo is loot" },
  { t: "single", p: "SING-gul", g: "one attacker at a time; still not a reason to chase" },
  { t: "skulled", p: "SKULD", g: "you keep nothing unless Protect Item is on" },
  { t: "unskulled", p: "un-SKULD", g: "three items, or four with the prayer; still not a bank tab" },
  { t: "teleblock", p: "TEL-ee-blok", g: "the spell that says the ditch is your room now" },
  { t: "vengeance", p: "VEN-jenss", g: "a hit you saved for their spec, not their auto" },
  { t: "smite", p: "smyt", g: "the prayer that looks at their prayer points, not your feelings" },
  { t: "overhead", p: "OH-ver-hed", g: "the prayer they can see; switch it or eat the style" },
  { t: "thrall", p: "thrawl", g: "a small dead thing that hits while you count" },
  { t: "invocation", p: "in-voh-KAY-shun", g: "ToA rack; add one after a clean raid, not after a wipe" },
  { t: "enrage", p: "en-RAYJ", g: "RS3 percent that taxes the pull; the wiki keeps the hour" },
  { t: "font", p: "font", g: "Telos colour; wrong one ends the room, not the HP bar" },
  { t: "streak", p: "streek", g: "kills in a row; the next mechanic is the tax" },
  { t: "kc", p: "kay-see", g: "kill count; a number, not a personality" },
  { t: "learner", p: "LUR-ner", g: "first seats; the wipe is the lesson you named" },
  { t: "scouter", p: "SKOW-ter", g: "the look before the pile; if you skip it you are the loot" },
  { t: "hopper", p: "HOP-er", g: "world jump; not a method, just weather" },
  { t: "crash", p: "krash", g: "someone else's world, now yours; official rules still apply" },
  { t: "anti", p: "AN-tee", g: "the run back to the ditch with protect item already on" },
  { t: "tank", p: "tank", g: "gear that lives until the freeze lands" },
  { t: "dps", p: "dee-pee-ess", g: "damage while they cannot step; not a reason to stand in multi" },
  { t: "brew", p: "broov", g: "Sara brew; it hits the tank, then you restore" },
  { t: "restore", p: "rih-STOR", g: "the sip after the brew so the prayer is not a rumour" },
  { t: "karambwan", p: "kuh-RAM-bwahn", g: "the third eat; same tick as the decision, not a flex" },
  { t: "combo eat", p: "KOM-boh eet", g: "food stacked so the next hit does not land on an empty tank" },
  { t: "tick eat", p: "tik eet", g: "eating for the hit about to land, not the one that already did" },
  { t: "freeze cycle", p: "freez SY-kul", g: "bind, then spec; never spec into the thaw" },
  { t: "barrage", p: "buh-RAHZH", g: "ice on a pile; still not a client" },
  { t: "entangle", p: "en-TANG-gul", g: "a longer bind; the rule is the same as ice" },
  { t: "snare", p: "snair", g: "a short bind; do not treat it like a kill" },
  { t: "tb", p: "tee-bee", g: "teleblock, said tired" },
  { t: "dds", p: "dee-dee-ess", g: "dragon dagger spec; a bar, not a personality" },
  { t: "ags", p: "ay-gee-ess", g: "armadyl godsword; keep it for a kill, not a flex" },
  { t: "claws", p: "klawz", g: "dragon claws; same rule as every spec" },
  { t: "voidwaker", p: "VOID-way-ker", g: "a later spec; the wiki keeps the numbers" },
  { t: "lightbearer", p: "LYTE-bair-er", g: "the ring that feeds the bar; it does not invent a freeze" },
  { t: "salve", p: "salv", g: "the amulet for undead; wear it or stop quoting the trip" },
  { t: "slayer helm", p: "SLAY-er helm", g: "the mask that pays on task; off task it is a hat" },
  { t: "task", p: "task", g: "the assignment; skip tables live on the wiki" },
  { t: "konar", p: "KOH-nar", g: "a slayer master with a location; confirm it before the run" },
  { t: "burst", p: "burst", g: "barrage's cousin in the slayer cave; still not a script" },
  { t: "cannon", p: "KAN-un", g: "a rotating tax on slayer; set it, then pay attention" },
  { t: "priff", p: "prif", g: "Prifddinas, said tired; Song built it, VoS stays off Old School" },
  { t: "ge tax", p: "jee tax", g: "the cut on the exchange; public, not a tip" },
  { t: "world hop", p: "wurld hop", g: "changing instances; not a personality" },
  { t: "deadman", p: "DED-man", g: "a mode with its own skull; confirm it is live before you quote it" },
  { t: "lms", p: "el-em-ess", g: "Last Man Standing; a different bag from the ditch" },
  { t: "bh", p: "bee-aitch", g: "Bounty Hunter; do not mix that bag with wildy gear" },
  { t: "pvp world", p: "pee-vee-pee wurld", g: "combat everywhere the rules say; still not the ditch" },
  { t: "clan call", p: "klan kawl", g: "who to hit in multi; one voice, or you are the pile" },
  { t: "target", p: "TAR-get", g: "the body the pile agreed on" },
  { t: "loot key", p: "loot kee", g: "BH prize talk; confirm the live page" },
  { t: "death cost", p: "deth kost", g: "RS3 tax for dying; not an OSRS skull" },
  { t: "revo", p: "REV-oh", g: "revolution bar; a camp, not a secret" },
  { t: "manual", p: "MAN-yoo-ul", g: "you click the abilities; the bar is still public" },
  { t: "camp", p: "kamp", g: "the style you stay on; switches are a later sentence" },
  { t: "switch", p: "swich", g: "gear you change mid-pull; count it or eat the wipe" },
  { t: "ult", p: "ult", g: "ultimate ability; spend it on a phase, not a flex" },
  { t: "adren", p: "uh-DREN", g: "adrenaline; the bar that makes the ult honest" },
  { t: "vuln", p: "vuln", g: "vulnerability; a public debuff, not a private Discord" },
  { t: "codeword", p: "KOHD-wurd", g: "what the pile says; if you invent one you are already late" },
  { t: "bank pin", p: "bank pin", g: "the number you do not export" },
  { t: "pin", p: "pin", g: "same as bank pin; keep it off the clip" },
  { t: "world", p: "wurld", g: "the instance number; twelve letters is the name, not this" },
  { t: "hiscores", p: "HY-skorz", g: "public boards; fail-soft if the lookup sleeps" },
  { t: "wiki", p: "WIK-ee", g: "the page that wins on numbers" },
  { t: "patch note", p: "pach noht", g: "what actually shipped; blogs do not beat it" },
  { t: "jmod", p: "jay-mod", g: "Jagex staff; titles change, the directory is a snapshot" },
  { t: "iron", p: "EYE-urn", g: "an account that will not trade; not a personality" },
  { t: "uim", p: "yoo-eye-em", g: "ultimate ironman; the bag is the bank" },
  { t: "hcim", p: "aitch-see-eye-em", g: "hardcore; one death is the story" },
  { t: "gim", p: "jim", g: "group iron; the chest is shared, the wipe is still yours" },
  { t: "maxed", p: "MAXT", g: "ninety-nines; still not a reason to over-risk" },
  { t: "fire cape", p: "fire kayp", g: "Jad's receipt; wear it or stop quoting the cave" },
  { t: "infernal", p: "in-FUR-nul", g: "Zuk's receipt; blobs still wipe learners" },
  { t: "quest cape", p: "kwest kayp", g: "the list is done; the street is still the street" },
  { t: "diary", p: "DY-uh-ree", g: "achievement cape talk; confirm the tier on the wiki" },
  { t: "partyhat", p: "PAR-tee-hat", g: "a Christmas cone; identification, not a price on this desk" },
  { t: "phat", p: "pee-hat", g: "partyhat, said tired" },
  { t: "ge", p: "jee-ee", g: "Grand Exchange; tax is public" },
];

export function utcDay(now = Date.now()) {
  return Math.floor(now / 86_400_000);
}

function mulberry32(a: number) {
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function todaysWords(all: typeof WORDS, now = Date.now()) {
  const rng = mulberry32(utcDay(now) ^ 0xb0b);
  const copy = all.slice();
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy.slice(0, Math.min(48, copy.length));
}

export function bobWord(now = Date.now()) {
  const dayList = todaysWords(WORDS, now);
  const i = Math.floor(now / 30_000) % dayList.length;
  return dayList[i];
}

