export const WORDS = [
  { t: "tick", p: "tik", g: "point-six of a second. The whole game is this." },
  { t: "skull", p: "skul", g: "you chose the fight. The tax is the bag." },
  { t: "protect item", p: "pruh-TEKT EYE-tem", g: "one piece you refuse to lose. Put it on before the ditch." },
  { t: "freeze", p: "freez", g: "ice first. Spec during the hold, not after they step." },
  { t: "immunity", p: "ih-MYOO-nih-tee", g: "the thaw. A spec here is a gift." },
  { t: "tick eat", p: "tik eet", g: "eat for the hit about to land, not the one that already did." },
  { t: "combo eat", p: "KOM-boh eet", g: "food, brew, karambwan as one decision." },
  { t: "karambwan", p: "kuh-RAM-bwahn", g: "the third bite. Same tick. Not a flex." },
  { t: "brew", p: "broov", g: "Sara brew fills the tank. Restore after or the prayer dies." },
  { t: "restore", p: "rih-STOR", g: "the sip that makes the brew honest." },
  { t: "spec", p: "spek", g: "a bar you spend on a kill. Not a personality." },
  { t: "ags", p: "ay-gee-ess", g: "keep it for the freeze. Flexing it is how you donate." },
  { t: "claws", p: "klawz", g: "same rule as every spec. Bar, then eat." },
  { t: "dds", p: "dee-dee-ess", g: "dragon dagger. Cheap bar. Still a bar." },
  { t: "smite", p: "smyt", g: "you are looking at their prayer, not their armour." },
  { t: "overhead", p: "OH-ver-hed", g: "the prayer they can see. Switch it or eat the style." },
  { t: "vengeance", p: "VEN-jenss", g: "saved for their spec. Wasted on an auto." },
  { t: "teleblock", p: "TEL-ee-blok", g: "the ditch is the room now." },
  { t: "tb", p: "tee-bee", g: "teleblock, said tired." },
  { t: "multi", p: "MUL-tee", g: "you brought a pile or you are the pile." },
  { t: "single", p: "SING-gul", g: "one attacker. Still not a reason to chase." },
  { t: "pile", p: "pyl", g: "everyone on one body. Call the name or leave." },
  { t: "PJ", p: "pee-jay", g: "whose fight it is. The timer is public." },
  { t: "risk", p: "risk", g: "the number you will laugh off. Gear lives under it." },
  { t: "wildy", p: "WILL-dee", g: "north of the ditch. Official rules still win." },
  { t: "ditch", p: "dich", g: "the line. Cross it with protect item already on." },
  { t: "anti", p: "AN-tee", g: "the run home. Protect item first. Tele second." },
  { t: "hopper", p: "HOP-er", g: "a world change. Weather. Not a method." },
  { t: "crash", p: "krash", g: "their world, now yours. Rules did not change." },
  { t: "lms", p: "el-em-ess", g: "Last Man Standing. A different bag from the ditch." },
  { t: "bh", p: "bee-aitch", g: "Bounty Hunter. Do not mix that bag with wildy gear." },
  { t: "pvp world", p: "pee-vee-pee wurld", g: "combat where the world says. Still not the ditch." },
  { t: "unskulled", p: "un-SKULD", g: "three items. Four with the prayer. Not a bank tab." },
  { t: "skulled", p: "SKULD", g: "nothing kept unless protect item is on." },
  { t: "blighted", p: "BLY-tid", g: "wildy supplies. They do not come home." },
  { t: "loot key", p: "loot kee", g: "the bag they dropped. Open it in town, not on the pile." },
  { t: "rev", p: "rev", g: "revenant. Multi. You are not solo here." },
  { t: "thrall", p: "thrawl", g: "a small dead thing that hits while you count." },
  { t: "death charge", p: "deth charj", g: "the kill feeds the bar. Wiki keeps the cooldown." },
  { t: "lightbearer", p: "LYTE-bair-er", g: "feeds the bar. Does not invent a freeze." },
  { t: "voidwaker", p: "VOID-way-ker", g: "a later spec. Wiki keeps the numbers." },
  { t: "piety", p: "PY-uh-tee", g: "melee overhead. Drain is the tax." },
  { t: "rigour", p: "RIG-er", g: "range overhead. Same tax. Confirm the diary." },
  { t: "augury", p: "AW-gyuh-ree", g: "mage overhead. Same tax. Confirm the diary." },
  { t: "ancients", p: "AYN-shents", g: "the spellbook with the freeze. Ice, then the bar." },
  { t: "barrage", p: "buh-RAHZH", g: "ice on a pile. Still not a client." },
  { t: "burst", p: "burst", g: "the slayer cave cousin of barrage. Still not a script." },
  { t: "entangle", p: "en-TANG-gul", g: "a longer bind. Same rule as ice." },
  { t: "snare", p: "snair", g: "a short bind. Not a kill." },
  { t: "chinning", p: "CHIN-ing", g: "chinchompas on a stack. The cave is the teacher." },
  { t: "salve", p: "salv", g: "undead trip. Wear it or stop quoting the room." },
  { t: "slayer helm", p: "SLAY-er helm", g: "pays on task. Off task it is a hat." },
  { t: "task", p: "task", g: "the assignment. Skip tables live on the wiki." },
  { t: "konar", p: "KOH-nar", g: "a master with a room. Read the room before the run." },
  { t: "cannon", p: "KAN-un", g: "rotating tax on slayer. Set it. Then look." },
  { t: "cannonball", p: "KAN-un-bawl", g: "the ammo. Giants' Foundry and the furnace both make it." },
  { t: "priff", p: "prif", g: "Prifddinas. Song built it. VoS stays off Old School." },
  { t: "vos", p: "vee-oh-ess", g: "Voice of Seren. RuneScape clan. Not an Old School hour." },
  { t: "ge tax", p: "jee tax", g: "the cut on the exchange. Public. Not a tip." },
  { t: "ge", p: "jee-ee", g: "Grand Exchange. The booth does not owe you a flip." },
  { t: "hiscores", p: "HY-skorz", g: "public boards. If they sleep, the desk stays quiet." },
  { t: "wiki", p: "WIK-ee", g: "the page that wins on numbers." },
  { t: "patch note", p: "pach noht", g: "what shipped. A blog does not beat it." },
  { t: "jmod", p: "jay-mod", g: "Jagex staff. Titles move. The directory is a snapshot." },
  { t: "iron", p: "EYE-urn", g: "will not trade. Still dies to the same mechanic." },
  { t: "uim", p: "yoo-eye-em", g: "the bag is the bank." },
  { t: "hcim", p: "aitch-see-eye-em", g: "one death is the story." },
  { t: "gim", p: "jim", g: "shared chest. The wipe is still yours." },
  { t: "maxed", p: "MAXT", g: "ninety-nines. Still not a reason to over-risk." },
  { t: "fire cape", p: "fire kayp", g: "Jad's receipt. Wear it or stop quoting the cave." },
  { t: "infernal", p: "in-FUR-nul", g: "Zuk's receipt. Blobs still wipe learners." },
  { t: "quest cape", p: "kwest kayp", g: "the list is done. The street is still the street." },
  { t: "diary", p: "DY-uh-ree", g: "the cape talk. Confirm the tier on the wiki." },
  { t: "clog", p: "klog", g: "collection log. A slot. Not a personality." },
  { t: "partyhat", p: "PAR-tee-hat", g: "a Christmas cone. Identification. Not a price on this desk." },
  { t: "phat", p: "pee-hat", g: "partyhat, said tired." },
  { t: "kc", p: "kay-see", g: "kill count. A number. Not a personality." },
  { t: "learner", p: "LUR-ner", g: "first seats. Name the wipe before the drop." },
  { t: "enrage", p: "en-RAYJ", g: "RuneScape percent that taxes the pull." },
  { t: "font", p: "font", g: "Telos colour. Wrong one ends the room." },
  { t: "streak", p: "streek", g: "kills in a row. The next mechanic is the tax." },
  { t: "invocation", p: "in-voh-KAY-shun", g: "ToA rack. Add one after a clean raid." },
  { t: "death cost", p: "deth kost", g: "RuneScape tax for dying. Not an Old School skull." },
  { t: "revo", p: "REV-oh", g: "revolution bar. A camp. Not a secret." },
  { t: "manual", p: "MAN-yoo-ul", g: "you click the abilities. The bar is still public." },
  { t: "camp", p: "kamp", g: "the style you stay on." },
  { t: "switch", p: "swich", g: "gear you change mid-pull. Count it or eat the wipe." },
  { t: "ult", p: "ult", g: "ultimate. Spend it on a phase." },
  { t: "adren", p: "uh-DREN", g: "the bar that makes the ult honest." },
  { t: "vuln", p: "vuln", g: "a public debuff. Not a private Discord." },
  { t: "necro", p: "NEK-roh", g: "RuneScape combat style. Residual souls are the grammar." },
  { t: "bank pin", p: "bank pin", g: "the number you do not put on a clip." },
  { t: "world", p: "wurld", g: "the instance. Twelve letters is the name, not this." },
  { t: "stronghold", p: "STRONG-hold", g: "four floors under Barbarian Village. The box is upstairs." },
  { t: "catablepon", p: "kat-uh-BLEP-on", g: "they drain Strength. That is the wipe." },
  { t: "greegree", p: "GREE-gree", g: "Ape Atoll. Wear it or the guards remember you." },
  { t: "edicts", p: "EE-dikts", g: "Guthix's last law. Old School still lives under it." },
  { t: "sixth age", p: "siksth ayj", g: "RuneScape after the edicts. Do not file it on an Old School plate." },
  { t: "justiciar", p: "jus-TISH-ee-ar", g: "Saradomin's plate. White stone. Not a flex title." },
  { t: "void", p: "voyd", g: "the pest kit. On task it pays. Off task read the room." },
  { t: "prayer flick", p: "PRAY-er flik", g: "on for the hit. Off for the tick. Miss it and you ate for nothing." },
  { t: "safe spot", p: "sayf spot", g: "a tile they cannot reach. Learn it. Then leave it." },
  { t: "afk", p: "ay-eff-kay", g: "the method that pays while you look away. Fast is the other column." },
  { t: "alch", p: "alk", g: "high alchemy. The fire staff is the grammar." },
  { t: "stamina", p: "STAM-ih-nuh", g: "the sip that keeps the run on. Run out and you walked." },
  { t: "divine", p: "dih-VINE", g: "a potion that holds the stat. Confirm the dose on the wiki." },
  { t: "poh", p: "pee-oh-aitch", g: "the house. Pool, then the next room. Tabs are the grammar." },
  { t: "house tab", p: "hows tab", g: "the teleport home. Pool first if you paid for the house." },
  { t: "rc", p: "ar-see", g: "Runecraft. Essence, then the altar. The wiki keeps the lap." },
  { t: "gotr", p: "got-er", g: "Guardians of the Rift. Old School room. Confirm the points." },
  { t: "bloods", p: "bludz", g: "blood runes. Zeah or the altar. Confirm the book." },
  { t: "souls", p: "sohlz", g: "soul runes. Menaphos on RuneScape. Arceuus on Old School." },
  { t: "sepulchre", p: "SEP-ul-ker", g: "Hallowed. Sixty-two to start talking. The floor is the teacher." },
  { t: "mlm", p: "em-el-em", g: "Motherlode. The hopper is the method. Pay dirt is the tax." },
  { t: "foundry", p: "FOWN-dree", g: "Giants' Foundry. The mould is the method. The commission is the tax." },
  { t: "blast furnace", p: "blast FUR-niss", g: "Keldagrim. Coal, then the bar. Confirm the world." },
  { t: "forestry", p: "FOR-iss-tree", g: "the event on the tree. The root is extra. The axe is still the axe." },
  { t: "wintertodt", p: "WIN-ter-tot", g: "the fire in the north. Warmth is the mechanic. The crate is the receipt." },
  { t: "tempoross", p: "TEM-poh-ross", g: "the spirit in the boat. Douse, then harpoon. Confirm the dock." },
  { t: "herbiboar", p: "HER-bih-bor", g: "Fossil Island. Tracks, then the stun. Herbs are the tax." },
  { t: "birdhouse", p: "BURD-hows", g: "Fossil Island. Ten minutes. Then empty the nest." },
  { t: "contract", p: "KON-trakt", g: "farming guild paper. The patch is the assignment." },
  { t: "tithe", p: "tythe", g: "Hosidius farm. Water, then the fruit. The points are the receipt." },
  { t: "zeah", p: "ZEE-uh", g: "Great Kourend. Blood runes live here. Confirm the book." },
  { t: "varlamore", p: "VAR-luh-mor", g: "the western sun. Colosseum and moons. Confirm the ship." },
  { t: "colosseum", p: "kol-uh-SEE-um", g: "Sol Heredit. Invocations again. The wave is the teacher." },
  { t: "cg", p: "see-jee", g: "Corrupted Gauntlet. The prep is the raid. Hunllef is the exam." },
  { t: "hunllef", p: "HUN-lef", g: "the Gauntlet boss. Tiles and prayer. The staff is a receipt." },
  { t: "cox", p: "koks", g: "Chambers of Xeric. Olm is the last room. Learn the hand." },
  { t: "tob", p: "tee-oh-bee", g: "Theatre of Blood. Verzik is the last seat." },
  { t: "toa", p: "tee-oh-ay", g: "Tombs of Amascut. Invos stay on the rack you chose." },
  { t: "olm", p: "olm", g: "Chambers. The last room. Learn the hand." },
  { t: "verzik", p: "VER-zik", g: "Theatre. The last seat. Do not stand in the wrong tile." },
  { t: "wardens", p: "WOR-denz", g: "ToA last room. Invos stay on the rack you chose." },
  { t: "zuk", p: "zuk", g: "the Inferno. The cape is a receipt. The blob is the teacher." },
  { t: "jad", p: "jad", g: "the cave. Healers if you panic. Prayer if you look." },
  { t: "dt2", p: "dee-tee-too", g: "Desert Treasure two. Four bosses. Awakened is a later tax." },
  { t: "whisperer", p: "WISS-per-er", g: "the sanity bar. Look away from the wrong song." },
  { t: "leviathan", p: "leh-VY-uh-thin", g: "the dam. Smoke is the wipe. Boulders are the grammar." },
  { t: "vardorvis", p: "var-DOR-vis", g: "the axe. Tiles. Head is the later exam." },
  { t: "duke", p: "dook", g: "Duke Sucellus. The brew, the gas, the smash. Name them." },
  { t: "araxxor", p: "uh-RAX-or", g: "the spider. Acid and eggs. RuneScape had it first. Old School has it now." },
  { t: "yama", p: "YAH-mah", g: "the contract demon. Confirm the wiki before the pull." },
  { t: "huey", p: "HYOO-ee", g: "Hueycoatl. The snake on the mountain. Mass is allowed. Mechanics are not optional." },
  { t: "kbd", p: "kay-bee-dee", g: "King Black Dragon. The task dragon is a different sheet." },
  { t: "qbd", p: "kyoo-bee-dee", g: "Queen Black Dragon. Stays on Bosses." },
  { t: "corp", p: "korp", g: "Corporeal Beast. Spears. The core is the wipe." },
  { t: "nex", p: "neks", g: "Zarosian. Smoke, shadow, blood, ice. Call the phase." },
  { t: "nightmare", p: "NYTE-mair", g: "the sister. Totems first. Husk is the wipe if you sleep." },
  { t: "telos", p: "TEL-oss", g: "the font. Enrage is the tax. RuneScape keeps the streak." },
  { t: "solak", p: "SOH-lak", g: "the grove. Split the roles. Confirm the week." },
  { t: "raksha", p: "RAHK-shah", g: "Anachronia. The shadow is the wipe." },
  { t: "kerapac", p: "KEH-ruh-pak", g: "the dragonkin. Time is the mechanic." },
  { t: "rasial", p: "RAY-zee-ul", g: "Necromancy exam. The grimoire is public." },
  { t: "amascut", p: "AH-mah-skut", g: "the devourer. Sanctum is the later room." },
  { t: "arch-glacor", p: "arch GLAY-kor", g: "the boss. The slayer glacor is a different card." },
  { t: "menaphos", p: "men-AH-fos", g: "the gated city. Soul runes. RuneScape keeps the gate." },
  { t: "anachronia", p: "uh-NAK-ruh-NEE-uh", g: "the island that should not be there. Dinosaurs. Confirm the farm." },
  { t: "sailing", p: "SAY-ling", g: "the boat skill. Confirm the patch. A blog does not launch the ship." },
  { t: "still", p: "stil", g: "the picture on the plate. One source. Not the whole atlas." },
  { t: "plate", p: "playt", g: "the banner. Twelve letters sit over the pack." },
  { t: "stamp", p: "stamp", g: "a skill on the still. Wheel scales the one you picked." },
  { t: "bob", p: "bob", g: "a cat. Unferth's. He already knew the street." },
  { t: "postie", p: "POH-stee", g: "Pete. The click curve. First talk is cheap." },
  { t: "workwork", p: "wurk-wurk", g: "a name the plate remembers once. Then it clears." },
];

export function utcDay(now = Date.now()) {
  return Math.floor(now / 86_400_000);
}

function mulberry32(a: number) {
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function todaysWords(all: typeof WORDS, now = Date.now()) {
  const rng = mulberry32(utcDay(now) ^ 0xb0b);
  const copy = all.slice();
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy.slice(0, Math.min(48, copy.length));
}

export function bobWord(now = Date.now()) {
  const dayList = todaysWords(WORDS, now);
  const i = Math.floor(now / 30_000) % dayList.length;
  return dayList[i];
}
