import { SKILLS, type Skill } from "./skills";

export type SkillGuide = {
  skill: Skill;
  slug: string;
  hook: string;
  afk: string;
  fast: string;
  watch: string;
  early: string;
  mid: string;
  late: string;
  wear: string;
  need: string;
  money: string;
  wiki: string;
  train: string;
};

type Note = {
  afk: string;
  fast: string;
  watch: string;
  early: string;
  mid: string;
  late: string;
  wear: string;
  need: string;
  money: string;
  page: string;
  train?: string;
};

function osrsWiki(page: string) {
  return `https://oldschool.runescape.wiki/w/${page}`;
}
function rs3Wiki(page: string) {
  return `https://runescape.wiki/w/${page}`;
}

const OSRS_NOTE: Record<string, Note> = {
  attack: {
    need: "No quest gate. Waterfall Quest, Fight Arena, and Tree Gnome Village dump Attack if you run them. Dragon scimitar wants Monkey Madness I. Whip wants a slayer level, not an Attack level.",
    money: "Crabs cost nothing but time. NMZ costs points and absorption. Slayer pays the hour. A whip you cannot replace is not a training method.",
    early: "1–40. Quests dump a chunk of Attack if you run them, but the floor is still a weak monster you can leave on. Cows are a classroom. Ammonite crabs and sand crabs are the first real hour: they aggress, they hit soft, and you can bury the bones or ignore them. Iron through mithril on a scimitar you can drop. Do not buy a whip for this bracket.",
    mid: "40–70. The scimitar that matches the level is enough. Slayer is the efficient room because the XP lands on the combat style you clicked and the points buy skips later. Controlled is a split across Attack, Strength, and Defence — use it when you want all three to move, not when you are rushing one number. NMZ exists. It is a dream you already understand or you skip it. Sulphur nagua and the live melee page own whatever the current mid camp is.",
    late: "70+. Abyssal whip or the stab the task actually wants. Slayer helm on task. Boss rooms and raids stay on Bosses. Training Attack at 90 by camping crabs is legal and slow. The wiki training page owns the current fastest monster.",
    wear: "Weapon first, then the helm the assignment named. Cape you already own. Shield only if the room hits back hard enough to waste food. Slayer helm on task beats a fashion scim. Protect the prayer that matches the hit. A set you cannot replace is not a training method.",
    afk: "Crabs or a slayer task you can cannon. Afk means the monster stays on you and the food lasts. If you have to click every tile, it is not this column.",
    fast: "Slayer in the rooms that burst or that die to the style you already camp. NMZ only if you already know the absorption dream. Confirm the live training page before you buy a stack for one night.",
    watch: "Wrong attack style is the wipe. A scimitar you cannot replace is not a method. The monster page owns face covers and finish mechanics.",
    page: "Attack",
    train: "Pay-to-play_Melee_training",
  },
  strength: {
    need: "Same quests as Attack. Dragon defender is a Defence pilgrimage that makes Strength nicer later. No unique Strength quest dump worth routing around Attack.",
    money: "Same hour as Attack. Super strength is a drink, not a bank. Do not buy a second max set for this number.",
    early: "1–40. Same crabs as Attack. The style named Strength. A strength potion if you bought one — it is a boost, not a method. Quests that dump combat still dump this number.",
    mid: "40–70. The same slayer hour. Controlled splits the XP across the three melee stats. If you are rushing Strength, Accurate and Aggressive are not the same click — pick Aggressive and leave Controlled for the catch-up. NMZ and the live melee camp are the same rooms Attack already named.",
    late: "70+. The weapon Attack already unlocked. Strength is the max hit, not a second pilgrimage. Warhammer, hasta, or the crush the task wants. 99 Strength on crabs is legal. 99 Strength on Duradel is how the account actually gets there.",
    wear: "Same as Attack. Do not buy a second max set for this number. Strength bonus on the amulet is real. A strength amulet is not a method after 70.",
    afk: "Same crabs. Same task. Same absorption dream if you already run NMZ.",
    fast: "Slayer. The monster the melee page currently ranks. Controlled is a split, not a third skill.",
    watch: "A strength amulet is not a method after 70. Wrong style is still the wipe.",
    page: "Strength",
    train: "Pay-to-play_Melee_training",
  },
  defence: {
    need: "Same combat quests. Dragon defender is the first Defence unlock that changes a room. Barrows gloves from Recipe for Disaster sit on every account that intends to finish.",
    money: "Tank gear you will wear on the next task. Chinning Defence is a paste and a gp sink. Barrows tank is a joke you can tell twice.",
    early: "1–40. Train it on the same crabs. Hide or chain you can replace. Defence bonus is why you live. Do not sit in rune plate because a shop sold it.",
    mid: "40–70. Barrows tank when the money is a joke you can tell twice. Slayer. Defensive on a task you already take. The defender that matches the level.",
    late: "70+. The armour you will wear on the next task. Chinning Defence is optional and loud — confirm the live page before you buy a stack of grey. Bandos or the tank the raid sheet already named. This is not a fashion skill.",
    wear: "Tank the style that hits you. Helm on task. Protect the prayer that matches the room. Defender in the shield slot unless the room asked for a defender-off weapon.",
    afk: "Tank the same task. Crabs in Defensive if you insist on a pure Defence hour.",
    fast: "Slayer in the gear you will wear later. Chins only if the tile is yours and the page still ranks it.",
    watch: "Chinning Defence is a paste. Confirm the live page. A set you cannot replace is not a method.",
    page: "Defence",
    train: "Pay-to-play_Melee_training",
  },
  ranged: {
    need: "Animal Magnetism for Ava. Broad bolts want a slayer unlock. Blowpipe wants Zulrah. Bow of faerdhinen wants Song of the Elves. Chinchompas want Hunter.",
    money: "Ammo is the tax. Broads are the cheap hour. Chins are a stack you either farm or buy. Black chins are a wildy tax. Cannonballs are Slayer money, not this column.",
    early: "1–40. Iron through mithril knives or a shortbow you can drop. Crabs. Bone crossbow is a meme you outgrow. Quest XP from Horror from the Deep and the dwarf quests is real if you run them.",
    mid: "40–70. Broad bolts on a slayer task. Rune crossbow. Ava when you have it. MSN or the live mid camp the ranged page names. Cannon on every assignment that allows it.",
    late: "70+. Blowpipe or the bow the wiki ranks for that room. Chins only if the tile is yours — maniacal monkeys and the current chin room move. Twisted bow and crystal are PvM sentences, not a training paragraph. Colosseum stays on Bosses.",
    wear: "Ava. Blessed hide or the tank the room asks. Slayer helm on task. Assembler later. Cannon if the assignment allows it. Protect from Missiles only when the room shoots you.",
    afk: "Cannon on a task. Crabs with a crossbow. Chinchompas are not afk.",
    fast: "Burst is Magic. Chin the assignment the wiki still names. Broads on a cannon task is the honest mid-fast.",
    watch: "Colosseum and raids stay on Bosses. Black chins are a wildy tax. Empty ammo is the wipe.",
    page: "Ranged",
    train: "Pay-to-play_Ranged_training",
  },
  prayer: {
    need: "Restless Ghost and Priest in Peril if you need the early dump. Gilded altar wants 75 Construction or a world with a host. Rigour and Augury want the diary and a coin stack. Ectofuntus wants Priest in Peril and a grind you already understand.",
    money: "Bones are the whole skill. Big bones are the cheap hour. Dragon and superior are the fast hour. Ensouled heads are a Magic plus Prayer mix. Wildy altar is faster and a tax.",
    early: "1–43. Bones on any altar. Big bones when you can buy them twice. Protect from Melee at 43 is the first prayer that changes a room. Quests dump a little Prayer. Do not sit on a chaotic altar with a bank.",
    mid: "Gilded altar with dragon bones is the honest mid. 45 Eagle Eye, 52 Smite if you PvP, 70 Piety when the knights are done. Ectofuntus is slower and cheaper. Wildy altar is faster and a tax. Chaos altar is PvP adjacent — protect item, bag you will laugh off.",
    late: "Rigour and Augury if the diary and the money exist. Wildy altar only with a bag you will laugh off. 99 Prayer is a bone stack, not a secret. Ensouled dragon heads if the live page still ranks them.",
    wear: "Vestment if you have the set. Protect Item on the wildy altar. No max melee. No infernal cape required to offer a bone. A house tab and a pool if you own the host.",
    afk: "Gilded altar with bones you can buy again. A butler makes it less of a walk. Ectofuntus if you like the grind.",
    fast: "Wilderness altar if you accept the skull tax. Dragon or superior bones as the page ranks them.",
    watch: "The bag is the wipe. Chaos fanatic does not care that you were training. Do not unsaved-spec into a bone stack.",
    page: "Prayer",
  },
  magic: {
    need: "Standard spellbook from the start. Iban wants Underground Pass. Ancients want Desert Treasure I. Lunars want Lunar Diplomacy. Barrage rooms want 94 Ice Barrage or the live burst level the slayer page names.",
    money: "Runes are the tax. Splashing is slow on purpose and cheap. Burst and barrage eat death and blood. High alchemy is Magic plus gp, not a training secret.",
    early: "1–40. Strike spells on crabs. Splashing is slow on purpose. Teleports spend runes and teach the book. Enchant bolts if you already fletch. Do not buy a trident for this bracket.",
    mid: "55 Iban. 58–75 the slayer spellbook you actually use. Teleports spend runes. Alch on the walk. Burst dusts when the level and the ancient book are there. Smoke devil and the live burst list own the rest.",
    late: "94 Ice Barrage if you burst. Ancients for the room, standards for the utility, lunars for the string and humidify. Thralls if you have the book and the room. Raids stay on Bosses.",
    wear: "Ahrim or the magic tank the room asks. Occult when you have it. Slayer helm on task. God cape. Tormented later. The staff the spell actually uses — iban staff is not a trident.",
    afk: "Do not call splashing efficient. Alch while you run rooftops if you insist on a second XP drop.",
    fast: "Burst or barrage the slayer room the live page still names. Chinning is Ranged.",
    watch: "Immunity and the wrong spellbook. Empty death runes are the wipe. A freeze into a walk is PvP, not this hour.",
    page: "Magic",
    train: "Pay-to-play_Magic_training",
  },
  runecraft: {
    need: "Rune Mysteries. Enter the Abyss wants the miniquest. Guardians of the Rift wants the quest of the same name. Blood and soul want Sins of the Father and the levels. Raiments of the eye want the rift.",
    money: "Essence is the tax. Lavas can pay. Bloods and souls can pay. Guardians of the Rift is a room with a unique drop table. Empty pouches are a wasted trip, not a gp strategy.",
    early: "1–23 airs and the essence you already have. Ourania when the quest is done. Tiaras, not talismans, once you can craft them. The abyss is a skull — protect item.",
    mid: "Lava if you can stand the trip. Guardians of the Rift for a room and the outfit. Daeyalt if you own the hour in Darkmeyer. Wrath and the mid runes the live page still ranks.",
    late: "Bloods and souls as the live page ranks them. Zeah bloods are a sit. True bloods are a trip. Confirm which one still pays before you buy a stack of dark essence.",
    wear: "Pouches. Raiments if you have the set. Stamina. A tiara, not a joke hat. Blood essence if you own it. Colossal pouch later.",
    afk: "Guardians of the Rift or ZMI. Zeah bloods if that sit is still the hour.",
    fast: "Bloods and lavas as the live page still ranks them. Tick lavas are a VOD habit, not a requirement.",
    watch: "Pouch decay. Empty pouches are the wipe. Abyss is PvP adjacent. Do not unsaved-spec a rune stack into a pker.",
    page: "Runecraft",
  },
  construction: {
    need: "Demon Slayer is not this skill. A house tab wants a portal. Butler wants 40 Construction and the money. Crystal saw wants The Eyes of Glouphrie. Mahogany Homes wants the minigame unlocked in the relevant cities.",
    money: "Planks are the whole skill. Oak is cheap and slow. Teak is the honest mid. Mahogany is the sink. Mahogany Homes pays some of it back in points. Max house is the sink, not the method.",
    early: "1–33 oak larders if you must. Quests dump a little. Mahogany Homes as soon as it takes you — the contract is a room, not a side quest. A crude chair is a tutorial, not a 99.",
    mid: "50s teak. Servant. Plank sack if you have it. Oak dungeon doors if you are still poor. Mythical cape and the mounted glory are house unlocks, not XP.",
    late: "Mahogany tables or the rack the page still pays. Gnome benches. 83+ is where the house becomes a tool for other skills — pool, lectern, altar. Max house is the sink.",
    wear: "Crystal saw. Butler. Clothes do not matter. Planks do. A demon butler is faster. Stamina for Homes.",
    afk: "Mahogany Homes. Afk Construction is a polite lie. The click is the skill.",
    fast: "Mahogany tables or teak as the live page ranks them. Homes if you want the outfit and a calmer hour.",
    watch: "Plank make is Magic, not this skill. A butler you cannot pay is the wipe.",
    page: "Construction",
  },
  hitpoints: {
    need: "Follows every hit. No quest gate. NMZ absorption is a side room that still trains this number.",
    money: "Food is the grammar, not the method. Hitpoints XP is a side effect of the combat hour you already paid for.",
    early: "Follows every hit. Do not pilgrimage this number. Cows and crabs still fill it. Quests that dump combat dump this too.",
    mid: "The same slayer hour. Guthans or the food that lasts. Hitpoints does not have its own camp unless you invent one.",
    late: "99 happens while you play the other combat skills. A Hitpoints cape is a heal, not a training method.",
    wear: "Whatever the task already asked. Hitpoints cape later for the regen.",
    afk: "Any combat you already do.",
    fast: "The same slayer hour. NMZ if you already know the dream.",
    watch: "NMZ absorption is a side room. You cannot train Hitpoints without training something else. That is the design.",
    page: "Hitpoints",
    train: "Pay-to-play_Melee_training",
  },
  agility: {
    need: "The Grand Tree and Tourist Trap skip a painful early chunk. Seers diary teleport is a real course unlock. Hallowed Sepulchre wants Sins of the Father. Wilderness course is PvP adjacent.",
    money: "Marks of grace buy amylase and the graceful set. Sepulchre coffins are the side loot. Agility is a time skill. Do not expect the rooftop to pay for the hour.",
    early: "1–30. Quests skip a painful chunk if you run Tourist Trap and The Grand Tree. After that Draynor and Varrock rooftops teach the click. Fail less, not faster. Marks of grace are why rooftops beat a random dungeon at this level. Summer pie is a boost, not a personality.",
    mid: "The live training page still ranks Brimhaven Arena and then the Wilderness course as the fast mid rooms — both cost attention and, in the wildy, a bag. Rooftops from Canifis through Seers are the honest mid if you want marks and a calmer hour. Seers with the diary teleport is a real course, not flavour. Pollnivneach and Rellekka sit in this band too.",
    late: "62+ Hallowed Sepulchre is the fast room after Sins of the Father. Stamina, a private instance if you have it, and the floors you can actually clear. Ardougne rooftop remains the rooftop people finish 99 on. Rellekka is slower and quieter. Confirm rates on the wiki. They move.",
    wear: "Graceful. Stamina. Light boots and a spotted cape if you still run the wildy course. Food for fails. Sepulchre wants hitpoints and a brain, not a max melee set. Karamja gloves matter in the Arena. Weight is the mechanic.",
    afk: "Rooftops you fail less. Afk agility is a lie past the first two courses. The click is the skill.",
    fast: "Arena or Wilderness mid, Sepulchre late, as the live page still ranks them. Tickets and coffins are the side loot. Do not invent a third dungeon.",
    watch: "Marks slow down when you out-level a rooftop by twenty. A course you fail is not efficient. Wildy course is PvP adjacent. Protect item.",
    page: "Agility",
  },
  herblore: {
    need: "Druidic Ritual. Grim Tales and the diary lamps help. Amulet of chemistry is a drop, not a quest. Mastering Mixology is a room — confirm it is live on the training page before you treat it as the hour.",
    money: "Secondaries first. The herb is half the potion. Prayer potions and super sets you will drink are not a waste. A stack you cannot afford is not a method. Herbs from farming runs pay this skill.",
    early: "1–55. Attack, strength, and energy potions you will drink. Guam through ranarr. Do not clean herbs as a personality — the XP is a rounding error next to the potion. Quests dump a little.",
    mid: "Prayer potions, super attack, super strength, super restore. Contracts in the Farming Guild pay the grimy. Serum and the utility potions you actually use. Stamina if the live page still ranks the make.",
    late: "Saradomin brew, forgotten brew, super combat, and the potion the wiki ranks this month. Mixology if that room is live. 99 Herblore is a bank tab of secondaries, not a secret patch.",
    wear: "Amulet of chemistry if you own it. Banked secondaries. Clothes do not matter. A portable well is the other client.",
    afk: "Contracts and grimy you already farm. Cleaning is not afk training. It is a click you already had to do.",
    fast: "The potion the wiki ranks this month. Confirm it. A blog will sell you last year’s brew.",
    watch: "A stack you cannot afford is not a method. Empty vials are not the wipe — missing secondaries are.",
    page: "Herblore",
  },
  thieving: {
    need: "No gate. Ardougne diary changes knights. Rogue equipment wants the wilderness Rogues’ Castle minigame. Elves want Song of the Elves. Vyres want Sins of the Father. Pyramid Plunder wants Icthlarin’s Little Helper.",
    money: "Knights with rogue pay. Elves and vyres can pay. Stalls are pocket change. A blackjack room is gp plus XP if you can stand the click.",
    early: "1–40. Stalls and men. Cake stall in East Ardougne is a classroom. Fruit stalls in Hosidius when the favour or the diary is done. Do not sit on a master farmer at 1.",
    mid: "55 knights with the diary. Pyramid Plunder if you like the room. Blackjacking if you can stand the click — Bearded Bandit and the live page own the level. Master farmer for seeds, not for the 99.",
    late: "Vyres or elves as the live page ranks them. Rogue set doubles the coin. Dodgy necklace saves the stun. 99 Thieving is a click, not a camp.",
    wear: "Rogue if you want the double. Dodgy necklace. Food. No wildy bag on a knight. Shadow veil if you have the book.",
    afk: "Ardougne knights with the diary. Afk thieving still needs a food click.",
    fast: "Elves or vyres as the live page ranks them. Blackjacking if you already have the hands for it.",
    watch: "Stun. Food. The knight is not a PvP fight. A failed pick with an empty plate is the wipe.",
    page: "Thieving",
  },
  crafting: {
    need: "No gate. Lunar Diplomacy for String Jewellery. Giant Seaweed wants Fossil Island. Blowglass wants a furnace or the colony. Crafting guild wants 40.",
    money: "Gold jewellery can pay. Hide bodies are a sink or a sell depending on the hour. Seaweed and sand are the honest cheap hour. Battlestaves are a buyable.",
    early: "1–40. Leather and jewellery you can sell. Cowhide to leather is a classroom. Gold rings if the mould is in the bag. Do not cut uncut onyx at 1.",
    mid: "Glass from giant seaweed and buckets of sand. Gold bracelets or the jewellery the page names. Green through black d’hide. Superglass make if you have lunars.",
    late: "Blowglass and the staff the page ranks. 99 is a bank, not a flex. Onyx and zenyte are money, not a training paragraph, unless the live page says otherwise.",
    wear: "Needle. Crafting cape later. No combat set required. A charged amulet of glory is a teleport, not XP.",
    afk: "Seaweed and sand. Then the jewellery the page names. Hide bodies on a bank chest.",
    fast: "Battlestaves and dragonhide as ranked. Blowglass if that is still the hour.",
    watch: "Gold at the furnace is the old hour. Empty seaweed is the wipe for glass.",
    page: "Crafting",
  },
  fletching: {
    need: "No gate. Broads want a slayer unlock. Dragon darts want the tips. Bowstrings from flax or the shop.",
    money: "Broads are the cheap hour. Darts can pay or sink depending on tips. Magic longs are a buyable. Arrow shafts are pocket XP.",
    early: "1–40. Shafts and shortbows. Arrow shafts from logs you already cut. Shortbows you can alch or drop. Do not buy dragon darts for this bracket.",
    mid: "Broads on the slayer ring hour. Maple through magic longbows. Mithril and adamant darts if the tips exist. Stringing and heading are two different clicks — the page ranks which one is the hour.",
    late: "Darts if the tips exist. Dragon only if the money is a joke. Redwood shields if the live page still names them. 99 Fletching is a bank tab of tips.",
    wear: "Knife. Bank. Clothes do not matter. A fletching cape later.",
    afk: "Broad arrows. Darts if you have the tips. Stringing a full inventory is a sit.",
    fast: "The tip the wiki ranks. Confirm it. Stringing is not automatically the fast room.",
    watch: "Stringing is not automatically the fast room. Empty tips are the wipe.",
    page: "Fletching",
  },
  slayer: {
    need: "Smoke of the priest? No. Turael is the door. Helm wants 10, 20, 30, 40, 50, 60, 70 as the pieces unlock. Broads and the cannon are slayer shop unlocks. Boss tasks want the kill count and the courage.",
    money: "The assignment pays or it does not. Skip tokens are the real currency. Brimstone is Konar’s side chest. Do not farm a slow task because a streamer liked the drop table in 2019.",
    early: "Turael only to unlock the skill and finish a streak you intend to break. Mazchna and Vannaka are the first real lists. Buy the helm as soon as it exists. Broad bolts and a cannon unlock are the mid-early purchases that actually pay. Block list starts empty on purpose — you do not know your hates yet.",
    mid: "Chaeldar through Nieve or Steve. Cannon every task the assignment allows. Burst the dusts and the nechryael when the level and the spellbook are there. Konar is brimstone and a location lock. Take her when you want the chest, not when you want the fastest 99.",
    late: "Duradel. Skip list on the wiki. Burst and barrage the assignments that still say so. Boss tasks are Bosses pages, not a training paragraph. 99 Slayer is a skip sheet and a prayer, not a secret monster.",
    wear: "Slayer helm on task. The combat style the monster is weak to. Face cover the bestiary already named — nose peg, earmuffs, witchwood, elemental shield. Cannon in the rooms that allow it. Protect the prayer that matches the hit.",
    afk: "The task you can cannon or leave on a crab-like monster. Afk slayer still needs a check on the timer.",
    fast: "Burst and barrage assignments. Skip what the live page skips. Do not farm a slow task because a streamer liked the drop table in 2019.",
    watch: "Wrong helm. Wrong prayer. Bare-faced spectre. That is the wipe. The monster page owns the finish mechanic.",
    page: "Slayer",
  },
  hunter: {
    need: "No gate. Birdhouses want Fossil Island. Herbiboar wants 80 Hunter and Bone Voyage. Chinchompas want the level and a private tile. Hunter Guild rumours want Varlamore — confirm the live training page for the current rumour loop.",
    money: "Birdhouses pay nests on a timer. Red chins pay. Black chins pay more and cost a bag. Herbiboar pays herbs. Rumours pay the hunter loot the page names.",
    early: "1–40. Birds and kebbits. Crimson swifts on the beach. Gloves when the page says gloves. Copper longtails. Feldip weasels. Do not sit on a red chin tile at 20.",
    mid: "Birdhouses on a timer — that is the passive XP every account should already be running. Salamanders. Drift net if you like the fossil. Box traps at the level the page names. Hunter Guild rumours if that loop is live.",
    late: "Herbiboar. Red chins. Black chins only with a bag you will laugh off. Maniacal if the live page still ranks them. 99 Hunter is a mix of the timer and a tile, not one camp.",
    wear: "Camouflage if you have it. Graceful is fine. Protect item in the PK grounds. A hunter cape later. No slayer helm on a box trap.",
    afk: "Birdhouses on Fossil Island. The box trap you can leave if the creature stays.",
    fast: "Herbiboar or chinchompas as the live page ranks them. Rumours if that loop is the hour.",
    watch: "Black chins are a wildy tax. Empty birdhouses are a wasted 50 minutes. Confirm rumours on the wiki — a blog will invent a third guild.",
    page: "Hunter",
  },
  mining: {
    need: "No gate. Motherlode wants 30. Mining guild wants 60. Amethyst wants 92. Volcanic Mine wants 50 and the quest. Zalcano is a group skilling boss, not a rock.",
    money: "Iron is the old profit. Motherlode pays ores and a cleaner. Amethyst pays. Stars pay dust. A tick granite hour is XP, not gp.",
    early: "1–30. Copper, tin, iron. The pick matches the level. Quests help. Do not sit on runite at 40 because a video thumbnail said so. Power-mine iron if you want the click.",
    mid: "Motherlode is the afk room with pay-dirt and a cleaner. Granite is the tick room if you want to click. Stars are a world-event. Gem rocks if you like the chance. Volcanic Mine if you can stand the team. All of these are on the live page — rates move.",
    late: "Amethyst at 92. The rock the wiki currently ranks for raw XP. 3-tick granite is a VOD habit, not a requirement. Mining guild and the expert mining gloves matter if you own them. Calcified rocks if the live page still names them.",
    wear: "Best pick you can use. Prospector if you own the set. Celestial ring later. No slayer helm required on a rock. Expert mining gloves for the rocks they name.",
    afk: "Motherlode. Stars when they are up. Amethyst when the level is there.",
    fast: "The rock the wiki ranks for the tick this month. Confirm it. A blog will sell you last year’s tick. Volcanic Mine if the team is real.",
    watch: "A pick you cannot replace is not a method. The belt in the Foundry is Smithing. Empty pay-dirt is a wasted trip.",
    page: "Mining",
  },
  smithing: {
    need: "The Knight’s Sword dumps a chunk. Giants’ Foundry wants Sleeping Giants. Blast Furnace wants the minigame and ice gloves for gold. Goldsmith gauntlets want Family Crest.",
    money: "Bars you will use are not a waste. Gold at the furnace can pay. Foundry pays some of the bar back. Platebodies for a diary are a sink you already accepted.",
    early: "1–40. The bars you already mined. Bronze through steel. The Knight’s Sword. Do not smith rune plate at 40.",
    mid: "Giants’ Foundry is the honest mid room — mould, temperature, pour. Blast Furnace gold if you can stand the heat. Steel and mithril if you need the bars. Anvil cannonballs are gp, not XP.",
    late: "The bar the page ranks. Platebodies only for the diary. Addy and rune if the live page still pays the XP. 99 Smithing is a coal bag and a heat, not a secret anvil.",
    wear: "Ice gloves. Coal bag. Goldsmith gauntlets for gold. Apron is flavour. Foundry outfit if you own it.",
    afk: "Giants’ Foundry. Gold at a quiet furnace if you insist.",
    fast: "Blast Furnace bars the page still ranks. Foundry if that is still the hour.",
    watch: "The belt is the wipe. Empty coal is a wasted load. Blast Furnace is this client. Do not paste an RS3 rework paragraph here.",
    page: "Smithing",
  },
  fishing: {
    need: "No gate. Barbarian Fishing wants Alfred Grimhand’s Barcrawl and the miniquest. Tempoross wants 35. Aerial wants 43 and Bone Voyage. Angler outfit wants piscatoris and the minigame.",
    money: "Karambwan, anglerfish, and minnows can pay. Tempoross pays a crate. Trout you power-fish is XP, not gp. A shark you cannot cook is a bank tab.",
    early: "1–40. Shrimp through lobster. Fly fishing trout and salmon if you want the tick. Quests dump a little. Do not sit on a shark spot at 20.",
    mid: "Barbarian Fishing is the honest mid — Agility and Strength on the side. Aerial for the fossil. Tempoross for the crate and the outfit. Monkfish when the guild is yours.",
    late: "Minnows or the fish the wiki ranks. Infernal eels. Anglerfish. 99 Fishing is a sit or a crate, not a secret dock. Drift net is Hunter plus Fishing.",
    wear: "Best rod. Angler when you have it. No max melee on the dock. Dragon harpoon later. Fishing barrel if you own it.",
    afk: "Barbarian. Tempoross. Anglerfish on a quiet spot.",
    fast: "Minnows or the fish the wiki ranks. Aerial if you can stand the click.",
    watch: "A shark you cannot cook is a bank tab. Empty bait is the wipe. Tempoross still has a fire.",
    page: "Fishing",
  },
  cooking: {
    need: "Cook’s Assistant. Hosidius kitchen wants the diary. Cooking gauntlets want Family Crest. Myths’ guild range later.",
    money: "The fish you will eat are not a waste. Wines can be a buyable. Karambwans you will combo-eat are inventory, not a loss. Burning is the gp wipe.",
    early: "1–40. The fish you already caught. Shrimp through lobster. Meat if you must. Do not buy sharks for this bracket.",
    mid: "Karambwans. Hosidius if the diary is done — the range that does not burn is the whole mid. Wine if the grapes are already there. Swordfish and monkfish as you catch them.",
    late: "The same fish. Sharks, anglers, dark crabs. Wines if the stack is already there. 99 Cooking is a range and a gauntlet, not a recipe book.",
    wear: "Cooking gauntlets. Hosidius range. Clothes do not matter. A cooking cape later stops the burn.",
    afk: "Karambwans on the range that does not burn. 1-tick karambwan is a VOD habit, not a requirement.",
    fast: "The same fish on the range that does not burn. Wines if the page still ranks them.",
    watch: "Burning is the wipe. The diary is the fix. Empty fish is a wasted click.",
    page: "Cooking",
  },
  firemaking: {
    need: "No gate. Wintertodt wants 50. Making Friends with My Arm helps the crate. Forestry wants the event and the axe. A winter pie is a boost.",
    money: "Wintertodt pays a crate. Logs you already cut are the cheap hour. Forestry events pay the forestry loot. Do not buy magic logs to light them unless the page says the XP is the point.",
    early: "1–50. The logs you already cut. Normal through maple. A line of fires east of GE is a classroom. Do not sit in Wintertodt at 20 expecting the crate to carry you.",
    mid: "Wintertodt as soon as you can stand the cold. Warmth is the mechanic. Bruma roots, not oak. Forestry if the event is the hour — the event is the method, not the tree.",
    late: "The same winter until 99 if you like the crate. Forestry if the event is the hour. Redwood if you insist on a line. 99 Firemaking is a coat and a crate, not a secret log.",
    wear: "Warm clothing. Axe. Food. No infernal cape required. Pyromancer if you own the set. A piece of warm gear from the crate is the set.",
    afk: "Wintertodt. Forestry if the event is the hour. A fire line is not afk past the first inventory.",
    fast: "The same winter. Confirm if a forestry event outranks it this month.",
    watch: "Warmth. Bruma. Leaving the fire is the wipe. Wintertodt is this client. Do not paste an RS3 brazier paragraph here.",
    page: "Firemaking",
  },
  woodcutting: {
    need: "No gate. Woodcutting guild wants 60. Fossil Island wants Bone Voyage. Redwoods want 90. Forestry is an event on the tree you already cut. Sailing trees if that skill is live — confirm on the wiki.",
    money: "Yews and magics can pay. Teaks feed Construction. Redwoods are XP. Sulliusceps are a click. Bird nests are the side loot.",
    early: "1–30. Trees you can click twice. Oak at 15. Willow at 30. The axe matches the level. Do not sit on a redwood at 40.",
    mid: "Willows through teak. Fossil Island. Woodcutting guild. Forestry events on the tree you already cut. 2-tick teak is a VOD habit, not a requirement. Mahogany if you need the log.",
    late: "Redwoods. Forestry. Sulliusceps if you like the island. Bloodwood and the Sailing trees if the live page names them this week. 99 Woodcutting is an axe and a tree that lasts.",
    wear: "Best axe. Lumberjack if you own it. No combat set required. Dragon or crystal later. Felling axe only if the page still names it for forestry.",
    afk: "Forestry or redwoods. Yews if you like the nest.",
    fast: "The tree the wiki ranks. Teak ticks or sulliusceps if you can stand the click. Confirm Sailing trees before you sail for a log.",
    watch: "A felling axe you cannot drop is not a method. Empty inventory on a teak tick is the wipe.",
    page: "Woodcutting",
  },
  farming: {
    need: "No gate. Tithe wants 34 and Hosidius. Farming guild wants 45. Magic secateurs want Fairytale I. Bottomless bucket wants Hespori. Ultra compost is the grammar from the start.",
    money: "Herbs pay. Trees are a gp sink that buys the level. Tithe pays points and fruit. Contracts pay seeds. A dead tree is a wasted sapling.",
    early: "1–30. Hops and allotments. Compost from the start — that is not optional flavour. Potatoes are a classroom. Quests dump a chunk if you run them. Do not plant a magic tree at 15.",
    mid: "Fruit and hardwoods. Guild contracts. Catherby and the teleport you already own. Tithe for the outfit and the fruit. Calquat. Spirit trees later.",
    late: "Tree runs. Tithe if you want the room. The herb the page ranks. Hespori when the anima is up. 99 Farming is a teleports sheet and a compost bin, not a secret patch.",
    wear: "Magic secateurs. Bottomless bucket. Outfit if you own it. A seed dibber and a spade. No combat set on a cabbage.",
    afk: "Hardwoods and fruit. Contracts in the guild. Trees grow while you walk — that is the afk.",
    fast: "Tithe. Tree runs. Confirm the live herb if you are buying the seed for XP.",
    watch: "Payment. Compost. A dead tree is the wipe. Protection payment is cheaper than a dead magic.",
    page: "Farming",
  },
  sailing: {
    need: "Sailing is live. Pandemonium is the door. Crew, hull, and the facilities the current page lists. Do not paste a 2012 fishing hour onto a boat. Charting, courier, bounty, salvage, Barracuda Trials, and deep sea trawling are named rooms — take the ones the training page still ranks.",
    money: "Courier and bounty pay the task. Salvage pays the wreck. Trials pay the room. A hull you cannot dock is a bank tab. Confirm the live page before you buy a facility for gp.",
    early: "Pandemonium is the door. After that the wiki names courier tasks, bounty tasks, charting, shipwreck salvage, Barracuda Trials, and deep sea trawling. The first hull is a classroom. Do not buy a late facility for this bracket.",
    mid: "Crew and hull as the current training page lists them. Charting is map work. Salvage is a timer. Trials are a room. Pick the one you can repeat without tilting. Facilities that change the boat are the mid unlocks — confirm which ones still matter.",
    late: "The late sheet moves. Confirm the current Old School Sailing training page before you buy a hull you cannot dock. If a method is not on the wiki this week, it is not a method.",
    wear: "Whatever the Sailing page lists for that task. Not a slayer helm. Not a max melee set on a deck. Crew is the kit.",
    afk: "Salvage and the tasks you can leave on a heading. The live page owns which one is actually afk.",
    fast: "Trials or the task the training page currently ranks. Confirm it.",
    watch: "This skill is new enough that a blog will lie. Wiki wins. A hull you cannot dock is the wipe.",
    page: "Sailing",
  },
};

const RS3_NOTE: Record<string, Note> = {
  attack: {
    need: "No gate. Revolution is the door. Weakness combat is the grammar — the style the monster is weak to. Tiers are T40, T70, T80, T90, T95 as you own them. Invention perks sit on the piece you will keep.",
    money: "Slayer pays the hour. A T90 you cannot replace is not a training method. Camp vs switch is one bar, not two banks.",
    early: "1–40. Revolution on cows if you must, then a task. T40 weapon. Abilities first. Do not paste an Old School scimitar paragraph here. The combat academy is a classroom, not a 99.",
    mid: "60–80. The style the monster is weak to. T70–80 weapon. Slayer. Revolution plus a threshold you actually click. Overloads when Herblore allows, not before.",
    late: "90+. T90–95 as you own it. Boss rooms stay on Bosses. 99 and 120 combat are PvM hours. Training Attack on a dummy is legal and slow.",
    wear: "One bar. Slayer helm on task. Perks on the piece you will keep. Aura if you own it. Protect the prayer or curse that matches the hit.",
    afk: "Revolution on a task you already take. Aggression pots if the room needs them.",
    fast: "Slayer in the style that kills. The live combat page owns the dummy versus the task.",
    watch: "Do not paste an Old School freeze paragraph here. Wrong style is the wipe. Death cost is PvM grammar.",
    page: "Attack",
  },
  strength: {
    need: "Same as Attack. Strength is the hit on this client too. No unique Strength-only gate.",
    money: "Same hour as Attack. Do not buy a second set.",
    early: "Same task as Attack. Revolution. T40. The ability line that uses Strength, not a second pilgrimage.",
    mid: "The same bar. Strength is the hit. T70–80. Overloads when you can make them.",
    late: "The weapon Attack already unlocked. 99 and 120 happen on the same assignment.",
    wear: "Same as Attack. Do not buy a second set. Biting and the perks you will keep.",
    afk: "Same task.",
    fast: "The assignment that dies to melee.",
    watch: "Camp vs switch is one bar. Death cost is PvM grammar. Wildy is opt-in.",
    page: "Strength",
  },
  defence: {
    need: "Same combat hour. Tiers of tank. Devotion is an ability. Barricade is a button. Death cost is PvM grammar on this client.",
    money: "Tank the piece you will keep. Perks. A T90 tank you cannot replace is not a method.",
    early: "Tank the same hour. T40 armour. Food you can replace. Revolution still hits.",
    mid: "T70 tank. Prayer or curse that matches the hit. Devotion is a button, not a flex. Reflect.",
    late: "T90 tank on the piece you will keep. Perks. 99 Defence is a PvM hour. 120 if the skill still goes there on your sheet — confirm.",
    wear: "Armour for the style that hits you. Helm on task. Shield abilities if the room hits back. Keep-clicks are PvP, not this hour.",
    afk: "Tank the same hour. Revolution plus food.",
    fast: "Slayer in the gear you will keep.",
    watch: "Death cost is PvM grammar. Wildy is opt-in. Do not paste an Old School chinning paragraph here.",
    page: "Defence",
  },
  ranged: {
    need: "Ava analogue / ranged cape later. Tiers of bow and thrown. Chins if the room is yours. Ascension stays on Bosses.",
    money: "Ammo is cheaper on this client than Old School, but T90 still costs. Chins are a stack. Slayer pays.",
    early: "T40 bow or the thrown the page names. Revolution. Crablets are Mining. Do not paste knives-on-crabs here unless the live page still names that dummy.",
    mid: "T70–80. Weakness combat. Slayer. Needles and the thrown the page ranks. Corruption shot when you have it.",
    late: "T90–95. Chins only if the room is yours. Eldritch and the bow the PvM sheet names. Ascension commanders stay on Bosses.",
    wear: "Ava analogue if you have it. Helm on task. Perks on the bow you keep. Aura. Ammo that matches the weapon.",
    afk: "A task you can revolution. Aggression if the room needs it.",
    fast: "The style the monster is weak to. Chins if the tile is yours.",
    watch: "Ascension commanders stay on Bosses. Empty ammo is still the wipe.",
    page: "Ranged",
  },
  prayer: {
    need: "Protect prayers first. Curses want 92 and the temple. Gilded or the chapel you own. Powder of protection is PvP keep-click grammar, not a training method.",
    money: "Bones and ashes. Powder is a PvP sentence. Offering on an altar is the hour. Do not buy a second max set to bury a bone.",
    early: "Bones on any altar. Unlock the protection prayers. Ashes if you already have them. Do not sit in the wilderness with a bone stack.",
    mid: "Curses when the level is there. Gilded or the chapel you own. Dragon bones and the ash the page ranks. Ectofuntus if this client still pays it — confirm.",
    late: "The curse the PvM sheet names. Soulsplit is a room, not a flex. Turmoil line. 99 Prayer is a bone stack. Ancient bones if the live page still ranks them.",
    wear: "Vestment if you have it. Keep-clicks are PvP, not this hour. Auras if you own them.",
    afk: "Bones you can buy again. A portable if it stands.",
    fast: "The altar the page ranks. Ashes if they outrank bones this month.",
    watch: "Powder and sharks are PvP keep-clicks. A bone stack in the wild is the wipe.",
    page: "Prayer",
  },
  magic: {
    need: "Spellbooks as the dungeon wants them. Sunshine / Death’s Swiftness analogues. Invention on the staff you keep. Runes you can craft.",
    money: "Runes are cheaper here. Ability XP is the hour, not a splash. High alchemy still exists. Do not paste Ice Barrage as the 99.",
    early: "Strike and the first abilities. Revolution. The combat academy. Do not splash for a personality.",
    mid: "The spellbook the dungeon wants. Sunshine later. Vulnerability if the page still names it. Slayer in Magic.",
    late: "The ability line the wiki ranks. Death skulls are PvM sentences. Greater chain. 99 and the PvM hour. Magical dummy if the live page still pays it.",
    wear: "Magic tank. Helm on task. Perks on the staff you keep. Seasinger or the tank the room asks.",
    afk: "Revolution magic on a weak target.",
    fast: "The spell the wiki ranks for the task. Ability lock is the wipe if you cancel.",
    watch: "Ability lock. Wrong book. Do not paste an Old School freeze paragraph here.",
    page: "Magic",
  },
  runecraft: {
    need: "Rune Mysteries analogue. Runespan is the door. Abyss trips want the miniquest. Necromancy runes if that sheet still pays. Outfit from the span or the shop the page names.",
    money: "Runes can pay. Runespan is XP. Abyss is a trip. Pouches are the tax. Empty pouches are a wasted run.",
    early: "Runespan. Essence you already have. The first nodes. Do not abyss at 1.",
    mid: "Abyss trips. The rune the page names. Ourania analogue if live. Necro runes when that skill is on the account.",
    late: "The rune the live page ranks. Soul and blood if they still pay. 99 and 110 if the skill still goes there — confirm. Runespan late is legal and slower.",
    wear: "Pouches. Outfit if you own it. Infinite runes from the span are a method, not a bug.",
    afk: "The Runespan. The abyss if you want a trip.",
    fast: "The rune the live page ranks. Confirm necro runes before you treat them as the 99.",
    watch: "Empty pouches are the wipe. Do not paste Guardians of the Rift here — that is the other client.",
    page: "Runecrafting",
  },
  construction: {
    need: "A house. Fort Forinthry frames when the fort stands. Servant. Crystal saw analogue. Mahogany Homes if it exists on this client — confirm.",
    money: "Planks are the skill. Fort frames can be the hour. Max house is the sink. Portable if it stands.",
    early: "Oak if you must. Fort frames when the fort stands. A chair is a tutorial.",
    mid: "The furniture the wiki ranks. Servant. Flatpacks. Mahogany Homes if it exists on this client.",
    late: "Mahogany and the Fort hour. Max house is the sink. 99 Construction is a plank tab.",
    wear: "Crystal saw analogue. Planks. Clothes do not matter. Outfit if you own it.",
    afk: "Mahogany Homes if it exists on this client. Fort frames.",
    fast: "The furniture the wiki ranks. Fort if that is still the hour.",
    watch: "Planks first. Empty planks are the wipe. Do not paste oak larders as the 99 without checking this client’s page.",
    page: "Construction",
  },
  constitution: {
    need: "Follows every hit. Hitpoints is the Old School name. Food and soul split are the grammar.",
    money: "Food is the grammar. Constitution XP is a side effect of the combat hour.",
    early: "Follows every hit. Do not pilgrimage this number.",
    mid: "The same slayer hour. Guthix rest and the food that lasts.",
    late: "99 or 120 happens in combat. A Constitution cape is a heal.",
    wear: "Whatever the task asked. Cape later.",
    afk: "Combat you already do.",
    fast: "The same slayer hour.",
    watch: "Hitpoints is the Old School name. You cannot train this without training something else.",
    page: "Constitution",
  },
  agility: {
    need: "Gnome is the door. Hefin wants Prifddinas. Anachronia wants the island. Silverhawks are a charge — confirm they still exist on the live page before you buy a stack of feathers. Bikes near the archaeology campus if that sit is still live.",
    money: "Agility is a time skill. Silverhawks are a gp sink if they remain. Hefin pays the course. Anachronia pays the island.",
    early: "Gnome and the first rooftops. Burthorpe. Do not buy silverhawks for this bracket.",
    mid: "The course you fail less. Anachronia if that is the hour. Wilderness if you accept the tax — this client’s wildy is opt-in. Bandos and the mid courses the page names.",
    late: "Hefin in Prif. Silverhawks if you already own the hour and the page still lists them. Advanced gnome. 99 Agility is a course you fail less. Confirm if a bike sit outranks the course this month.",
    wear: "The outfit if you own it. No max tank required. Silverhawks on the feet if they remain. Weight is still the mechanic.",
    afk: "The course you fail less. Silverhawks if they remain. Bikes if that sit is live.",
    fast: "The course the wiki ranks. Silverhawks if owned and still listed.",
    watch: "A course you fail is not efficient. Confirm silverhawks — a patch can retire a boot. Do not paste Hallowed Sepulchre here.",
    page: "Agility",
  },
  herblore: {
    need: "Druidic Ritual analogue. Scroll of cleansing and the factory outfit. Portables if they stand. 120 Herblore is a real sheet on this client. Combination potions later.",
    money: "Secondaries first. 120 is a bank. Bombs and vulnerability if the live page ranks them. A stack you cannot afford is not a method.",
    early: "The potions you will drink. Attack and strength. Guam through ranarr. Cleaning is a rounding error next to the potion.",
    mid: "Prayer and restore. Contracts. Super sets. Portable well if it stands. Extreme potions when the level is there.",
    late: "The 120 sheet. Combination potions. Overloads you will drink. Vulnerability bombs if the page still ranks them. Portables if they stand.",
    wear: "Factory outfit if you own it. Secondaries first. A portable well is this client.",
    afk: "Contracts and grimy from the patch. Cleaning is not the 120.",
    fast: "The potion the page ranks. Confirm combination versus bomb this month.",
    watch: "A 120 herb hour is not an Old School paste. Missing secondaries are the wipe.",
    page: "Herblore",
  },
  thieving: {
    need: "Stalls are the door. Prif wants Plague’s End. Safecracking wants the level and the guild. Light fingers. Trahaearn or the elf the page names.",
    money: "Elves and safes can pay. Stalls are pocket change. Prif is the honest sit.",
    early: "Stalls. Men. The first safe. Dorgesh-Kaan if you like the room. Do not sit on a Prif elf at 20.",
    mid: "Prif or the stall the diary unlocked. Knights analogue. Pyramid if this client still has it. Safecracking when it unlocks.",
    late: "Elves, vyres, or the safe the wiki ranks. 99 and the sit you can repeat. Light fingers and the aura.",
    wear: "Light fingers. Food. No wildy bag. Outfit if you own it.",
    afk: "Prif or the stall the diary unlocked.",
    fast: "Elves, vyres, or the safe the wiki ranks.",
    watch: "Stun. The knight is not a PvP fight. Empty food is the wipe.",
    page: "Thieving",
  },
  crafting: {
    need: "Jewellery and hide. Urns if they still tag. Portable crafter if it stands. Invention later eats the junk.",
    money: "Jewellery can pay. Hide is a sink or a sell. Urns are XP. Portables if they stand.",
    early: "Leather and jewellery. Gold at the furnace. Do not cut onyx at 1.",
    mid: "Urns or glass if the page still names them. Dragonhide. Portable crafter if it stands.",
    late: "The hide or the jewellery the live sheet ranks. 99 Crafting is a bank. Invention components from the junk you already made.",
    wear: "Portable crafter if it stands. Clothes do not matter. Outfit if you own it.",
    afk: "Urns or glass. Jewellery on a chest.",
    fast: "The hide or jewellery the live sheet ranks.",
    watch: "Confirm the portable is live. Empty hide is the wipe.",
    page: "Crafting",
  },
  fletching: {
    need: "Shafts and a knife. Broads. Elder god arrows if the live page still ranks them. Invention later eats the junk.",
    money: "Tips can pay. Broads are the cheap hour. Elder god arrows are a late sheet — confirm cost.",
    early: "Shafts and shortbows. The logs you already cut.",
    mid: "Broads on a slayer hour. Maple through magic. Headless and the string.",
    late: "The tip the wiki ranks. Invention later eats the junk. Elder god arrows if that sheet still pays.",
    wear: "Knife. Bank. Outfit if you own it.",
    afk: "Broads. Staves if you have the logs.",
    fast: "The tip the wiki ranks.",
    watch: "Stringing is not automatically the fast room. Empty tips are the wipe.",
    page: "Fletching",
  },
  slayer: {
    need: "The first masters. Helm. Laniakea when the list is yours. 120 Slayer is a sheet. Ripper and edimmu stay on the bestiary. Weakness combat.",
    money: "The assignment pays or it does not. Skip is the real currency. High-end slayer is PvM money. Do not farm a slow task for a 2014 drop table.",
    early: "The first masters. Unlock the helm. Turael analogue. Broads. Do not take a ripper at 20.",
    mid: "Laniakea when the list is yours. Revolution the task. Weakness style. Cannon analogue if the assignment allows it.",
    late: "The assignment the page ranks. 120 is a sheet, not a flex. Boss tasks stay on Bosses. Skip list on the wiki.",
    wear: "Helm. Weakness style. Face cover the bestiary named. Perks on the piece you keep.",
    afk: "The task you can revolution. Aggression if the room needs it.",
    fast: "The assignment the page ranks. Skip list on the wiki.",
    watch: "Ripper and edimmu stay on the bestiary. Wrong helm is the wipe. Death cost is PvM grammar.",
    page: "Slayer",
  },
  hunter: {
    need: "Birds and traps. Anachronia. Big Game Hunter is a boss-skilling room — confirm the live page. Charming moths if that sheet still pays. Box traps you can leave.",
    money: "Chins can pay. Big Game is a rare table. Box traps are XP. Anachronia is a map.",
    early: "Birds and the first traps. Polar kebbits. Do not sit on a dinosaur at 20.",
    mid: "Box trap you can leave. Big game if the island is the hour. Grenwalls if they remain. Charming moths if that sheet still pays.",
    late: "The creature the wiki ranks. Anachronia. 99 Hunter is a trap you can repeat.",
    wear: "Outfit if you own it. Anachronia is a map. No max melee on a moth.",
    afk: "The box trap you can leave.",
    fast: "The creature the wiki ranks. Big Game if you can stand the room.",
    watch: "Confirm the live method. Big Game is a room with a wipe. Do not paste birdhouses here — that is the other client.",
    page: "Hunter",
  },
  mining: {
    need: "The mining-smithing rework owns the pick. Stamina on the rock. Seren stones want Prif. Concentrated gold and alaea as the page names them. Stone spirits if you use them. Do not paste Motherlode here.",
    money: "Ores feed Smithing. Concentrated gold can pay. Seren is XP. A tick you cannot repeat is not gp.",
    early: "The first rocks. The rework owns the pick. Copper and tin still teach the click. Do not sit on rune at 20.",
    mid: "The rock the rework still calls afk. Seren stones if they remain. Granite. Alaea crablets if named. Stone spirits if you own them.",
    late: "Concentrated if that is the hour. The tick the wiki ranks. 99 and the rock you can leave. Corrupted ore is Smithing’s cousin — confirm which skill it trains this month.",
    wear: "Best pick. Outfit if you own it. Imcando or the pick the page names. Do not paste Motherlode here.",
    afk: "The rock the rework still calls afk. Seren if they remain.",
    fast: "The tick the wiki ranks. Concentrated if you can stand the click.",
    watch: "The mining-smithing rework is this client. Empty stamina on the rock is the wipe. Motherlode is Old School.",
    page: "Mining",
  },
  smithing: {
    need: "The rework owns the furnace and the progress bar. Artisans’ Workshop. Burial if the page still pays. Hammer-tron later from Invention. Blast Furnace is Old School.",
    money: "Bars you will use. Burial is XP. Workshop can pay. A progress bar you cancel is a wasted heat.",
    early: "The bars you already mined. Bronze through steel. The rework’s first progress.",
    mid: "The furnace the rework named. Artisans’ Workshop. Corrupted ore if that is still a room.",
    late: "Burial if the page still pays. Progress the wiki ranks. 99 Smithing is a heat and a bar, not a platebody spam.",
    wear: "The hammer the rework named. Outfit if you own it. Hammer-tron if you augment.",
    afk: "The furnace the rework named. Workshop if you can leave it.",
    fast: "The bar and the progress the wiki ranks.",
    watch: "Blast Furnace is Old School. Cancelling the progress is the wipe.",
    page: "Smithing",
  },
  fishing: {
    need: "The first spots. Prif waterfall. Deep sea / frenzy if live. Menaphos if that is still a room. Urns if they still tag. Tavia’s rod later.",
    money: "Fish you will cook. Swarm can pay. Waterfall is XP. A shark you cannot cook is a bank tab.",
    early: "The first spots. Shrimp through lobster. Fly fish if you want the click.",
    mid: "The swarm or the spot the page calls afk. Menaphos if that is still a room. Barbarian if this client still has it. Urns if they still tag.",
    late: "The fish the wiki ranks. Prif waterfall. Wobbegong / frenzy if live. 99 Fishing is a sit.",
    wear: "Best rod. Outfit if you own it. Rod-o-matic if you augment.",
    afk: "The swarm or the afk spot. Waterfall if you can leave it.",
    fast: "The fish the wiki ranks. Frenzy if that room is live.",
    watch: "A shark you cannot cook is a bank tab. Empty bait is the wipe. Do not paste Tempoross here.",
    page: "Fishing",
  },
  cooking: {
    need: "The range that does not burn. Portable range if it stands. Gauntlets if this client still has them. Urns if they still tag.",
    money: "The fish you will eat. Wines if the stack is there. Burning is the gp wipe.",
    early: "The fish you already caught. Meat if you must.",
    mid: "The range that does not burn. Portables if they stand. Monkfish and the fish you already have.",
    late: "The same fish. Wines if the stack is there. 99 Cooking is a range.",
    wear: "Gauntlets if this client still has them. Portable range if live. Outfit if you own it.",
    afk: "The range that does not burn.",
    fast: "The fish you already caught. Portables if they stand.",
    watch: "Burning is the wipe. Empty fish is a wasted click. Hosidius is the other client.",
    page: "Cooking",
  },
  firemaking: {
    need: "Logs you already cut. Portable brazier if it stands. Bonfires. Pyro-matic later. Wintertodt is Old School.",
    money: "Logs you already cut. Bonfires are XP. A portable if it stands. Do not buy elder logs unless the page says the XP is the point.",
    early: "The logs you already cut. A line. Do not sit in a Wintertodt coat — that is the other client.",
    mid: "The line or the portable the page names. Bonfires. Acadia if named.",
    late: "The log the wiki ranks. Bonfires if that is still the hour. 99 Firemaking is a line.",
    wear: "No Wintertodt coat. That is the other client. Outfit if you own it. Pyro-matic if you augment.",
    afk: "The line or the portable the page names.",
    fast: "The log the wiki ranks.",
    watch: "Wintertodt is Old School. Leaving the fire is the wipe.",
    page: "Firemaking",
  },
  woodcutting: {
    need: "The first trees. Crystal and acadia as named. Ivy. Imcando axe later. Forestry is the other client.",
    money: "Logs feed Firemaking and Fletching. Crystal is XP. Golden bamboo if named. Nests are side loot.",
    early: "The first trees. Oak and willow analogues. The axe matches the level.",
    mid: "The tree you can leave. Crystal or acadia if named. Ivy. Teak and mahogany.",
    late: "The tick the wiki ranks. Imcando if you own the axe. 99 Woodcutting is a tree that lasts. Golden bamboo if that is still the hour.",
    wear: "Best axe. Outfit if you own it. Imcando or crystal. Augment later.",
    afk: "The tree you can leave. Ivy if it remains.",
    fast: "The tick the wiki ranks.",
    watch: "Forestry is the other client. Empty inventory on a tick is the wipe.",
    page: "Woodcutting",
  },
  farming: {
    need: "Allotments. Fort patch if it stands. Magic secateurs analogue. 120 Farming is a sheet. Scroll of life later. Ultra compost from the start.",
    money: "Herbs pay. Trees are a sink that buys the level. A dead tree is a wasted sapling. Fort patch if it stands.",
    early: "Allotments. Compost from the start. Hops. Do not plant a magic at 15.",
    mid: "Fruit and hardwoods. Fort patch if it stands. Contracts. Catherby analogue.",
    late: "Tree runs. The herb the 120 sheet ranks. 99 and 120 are a teleport sheet.",
    wear: "Secateurs. Outfit if you own it. Bottomless analogue if you own it.",
    afk: "Hardwoods and fruit. Trees grow while you walk.",
    fast: "Tree runs. The 120 herb sheet.",
    watch: "A dead tree is the wipe. Payment. Compost. Tithe is the other client unless this page still names it.",
    page: "Farming",
  },
  summoning: {
    need: "Gold charms. Wolf Whistle. Obelisk. Shards. Howl. This skill is RuneScape-only. Charms come from the combat you already do.",
    money: "Shards are the tax. Pouches you will use are not a waste. Spirit dumps you will never summon are a sink.",
    early: "Gold charms. The first pouches. Spirit wolf is a classroom. Do not buy crimson for this bracket.",
    mid: "Green and crimson from the task you already take. The pouch you will actually summon. Infuse at the obelisk, not on a walk.",
    late: "The pouch the wiki ranks. Howl and the special you will actually use. 99 Summoning is a charm tab and a shard stack.",
    wear: "Pouch. Obelisk. Shards first. No slayer helm required. Outfit if you own it.",
    afk: "Charms from the task you already take. Infusing a full inventory is a sit.",
    fast: "The pouch the wiki ranks.",
    watch: "This skill is RuneScape-only. Empty shards are the wipe. A familiar is not a pet.",
    page: "Summoning",
  },
  dungeoneering: {
    need: "Daemonheim is the door. Bound weapons. Complexity you can finish. Sinkholes if live. 120 is a sheet. Leave the overworld max set.",
    money: "Dungeoneering tokens buy the rewards. Floors are XP. A wipe on 5:5 is a reset, not gp.",
    early: "Floored complexity you can finish. Solo if you must. Bind the weapon you will keep. Do not rush 5:5 at 20.",
    mid: "5:5 when the team exists. Sinkholes if live. Resource dungeons as they unlock. Tokens into the shop you actually need.",
    late: "The floor the page ranks. 120 is a sheet. Occult and the high floors. Prestige if that loop remains.",
    wear: "The bound weapons the dungeon gave you. Leave the overworld max set. Proto-tool later.",
    afk: "Floors you can clear. Sinkholes if they are a sit.",
    fast: "The floor the page ranks. Sinkholes if they are live.",
    watch: "A wipe on 5:5 is a reset, not a method. Overworld gear is the wipe if you forget to bind.",
    page: "Dungeoneering",
  },
  divination: {
    need: "The first colony. Caches on a timer. Chronicle fragments if they still pay. Energy is the tax. Outfit from the skill.",
    money: "Energy and the product you actually weave. Caches are XP. A colony you cannot reach is not gp.",
    early: "The first colony. Pale wisps. Caches when they spawn. Do not sit on a high colony at 10.",
    mid: "The colony you can stand. Chronicle if that fragment still pays. Enriched cores. Convert or weave as the page ranks.",
    late: "The colony the wiki ranks. Energy first. 99 Divination is a crater. Ancestral if that colony remains.",
    wear: "Outfit if you own it. No combat set required. Chronicle if you carry it.",
    afk: "Caches on the timer. Wisps at the colony.",
    fast: "The colony the wiki ranks. Enriched if you can stand the click.",
    watch: "A colony you cannot reach is not a method. Empty energy is the wipe.",
    page: "Divination",
  },
  invention: {
    need: "Invention unlocks after the three skills the page names sit high enough to pass the tutorial. Then you discover, you disassemble junk, and you augment the first tool you will actually use. Blueprints first. A machine you cannot fuel is furniture.",
    money: "Components from the junk you already made. Siphons cost. Gizmos can be a sink. Augment the piece you will keep.",
    early: "Do not augment a scim you will throw away tomorrow. Discover the first blueprints. Disassemble the junk from the skills you already train. The tutorial is a classroom.",
    mid: "Combat-train an augmented weapon you already fight with, then siphon or disassemble at the item level the wiki ranks. Skilling tools work if you already cut or mine. Blueprints first.",
    late: "The machine and the item-level loop the training page still ranks. 120 is a sheet. Precise and the weapon perk you will keep beat a bank of unused gizmos. Ancient gizmos if that is still the hour.",
    wear: "The augmented gear you already fight or gather in. Do not invent a second bank tab named Invention.",
    afk: "Disassemble the junk you already make. Siphon the weapon you already swing.",
    fast: "Combat XP on an augmented piece, then the disassemble or siphon the page names. Discoveries first.",
    watch: "Augment the piece you will keep. A t70 you delete at 12 is a cost, not a flex.",
    page: "Invention",
  },
  archaeology: {
    need: "The first tutor and the first site. Restoration at the bench is half the skill. Precision and soil are the mechanics. Research unlocks the next site. Relics at the monolith. 120 is a sheet.",
    money: "Materials and restorations. Tetracompass if that loop is live. Sift soil if the spell is yours. A cracked artefact is a wasted hour.",
    early: "The first tutor and the first site. Restoration at the bench is half the skill. Precision and soil are the mechanics. A cracked artefact is a waste of the hour you already dug.",
    mid: "The cache and the collection the wiki ranks. Tetracompasses when that loop is live. Research is not optional flavour — it unlocks the next site. Relics you will actually activate.",
    late: "120 is a sheet. The rare excavation the page names. Do not paste a mining tick here. This is a restoration skill with a mattock.",
    wear: "Best mattock. Outfit if you own it. Precision, not a scimitar. Soil box. Imcando or Time and Space later.",
    afk: "The dig site you can leave on a hotspot that lasts.",
    fast: "The cache and the restoration loop the wiki ranks. Time sprite if you can stand the click.",
    watch: "A cracked artefact is the wipe. Confirm the live collection. Do not paste Motherlode here.",
    page: "Archaeology",
  },
  necromancy: {
    need: "City of Um. Rituals and combat. Kili upgrades. Death guard and skull lantern climb in tiers. Talent souls from rituals. Quests at this bracket have real skill gates — Construction, Slayer, Archaeology — confirm before you walk in. 120 is a combat skill on this client.",
    money: "Rituals print the souls. Combat prints the drops. Rasial stays on Bosses. A tier you skip is a weaker hour, not a saving.",
    early: "Necromancy trains two ways: rituals in the City of Um, and combat on undead. Early levels mix lesser communion-style rituals with the first Kili upgrades. Death guard and skull lantern climb in tiers. Do not skip the talent souls the rituals print — combat wants them.",
    mid: "Kili tasks step the gear every chunk of levels. Deathwarden or deathdealer as the page names the tank versus power split. Combat on the undead the training page lists. Multiply glyphs when they unlock.",
    late: "The wiki still ranks active rituals as the fast 90–120 hour, combat as the slower afk hour. Multiply glyphs and the necklace the page names if those remain live. Rasial and the other necro bosses stay on Bosses.",
    wear: "Necro weapon and armour of the tier Kili last unlocked. This is a style. Perks from Invention sit on the piece you will keep. Hybrid tank early if you cannot eat the room yet.",
    afk: "Combat on high-life undead the page names. Rituals are not afk if disturbances are the XP.",
    fast: "Rituals with the current glyph setup on the training page. Then the task.",
    watch: "Boss rooms stay on Bosses. A 2012 magic paste does not apply. Skipping Kili is the wipe.",
    page: "Necromancy",
  },
};

const OSRS_HOOK: Record<string, string> = {
  attack: "The style you clicked. Crabs, then the task.",
  strength: "The hit. Same hour as Attack.",
  defence: "The tank. Wear it before the room asks.",
  ranged: "Distance. Ammo is the tax.",
  prayer: "Bones on an altar. The bag is the wipe.",
  magic: "Burst or barrage. The room still has a face.",
  runecraft: "Essence, pouches, then the altar.",
  construction: "Planks. Homes if you want a calmer hour.",
  hitpoints: "The same slayer hour. Food is the grammar.",
  agility: "Rooftops, then Sepulchre after 62.",
  herblore: "Secondaries first. The potion the wiki ranks.",
  thieving: "Knights, then elves. Stun is the wipe.",
  crafting: "Glass and hide. Battlestaves if you bought them.",
  fletching: "Broads and tips. The bank is the room.",
  slayer: "The assignment. Skip tables live on the wiki.",
  hunter: "Birdhouses on a timer. Chins if the tile is yours.",
  mining: "Motherlode, then the rock the page ranks.",
  smithing: "Foundry or the furnace. Coal bag first.",
  fishing: "Barbarian or the crate. Cook what you catch.",
  cooking: "The range that does not burn.",
  firemaking: "Wintertodt. Warmth is the mechanic.",
  woodcutting: "The tree the wiki ranks. Forestry is an event.",
  farming: "Compost from the start. Trees run while you walk.",
  sailing: "Pandemonium, then the task the page still ranks.",
};

const RS3_HOOK: Record<string, string> = {
  attack: "Revolution. Weakness combat. One bar.",
  strength: "The hit. Same assignment as Attack.",
  defence: "The tank. Death cost is PvM grammar.",
  ranged: "Tiers of bow. Chins only if the room is yours.",
  prayer: "Bones and curses. Soulsplit is a room.",
  magic: "Abilities, not a splash. The book the dungeon wants.",
  runecraft: "Runespan, then the abyss trip.",
  construction: "Planks. Fort frames when the fort stands.",
  constitution: "The same slayer hour. Food is the grammar.",
  agility: "The course you fail less. Hefin in Prif.",
  herblore: "120 is a sheet. Secondaries first.",
  thieving: "Prif or the safe. Stun is the wipe.",
  crafting: "Jewellery and hide. Portables if they stand.",
  fletching: "Broads and tips. Invention eats the junk later.",
  slayer: "Laniakea when the list is yours. Skip on the wiki.",
  hunter: "The box trap you can leave. Anachronia is a map.",
  mining: "The rework owns the pick. Not Motherlode.",
  smithing: "The rework owns the heat. Not Blast Furnace.",
  fishing: "The swarm or the waterfall. Cook what you catch.",
  cooking: "The range that does not burn. Portables if live.",
  firemaking: "A line or a brazier. Not Wintertodt.",
  woodcutting: "The tree you can leave. Not Forestry.",
  farming: "120 is a sheet. Compost from the start.",
  summoning: "Charms, then the pouch. The familiar is not a pet.",
  dungeoneering: "Floors. Bind the weapon you will keep.",
  divination: "Wisp to crater. Caches on the timer.",
  invention: "Augment the piece you will keep.",
  archaeology: "Dig, then restore. A crack is the wipe.",
  necromancy: "Rituals and Kili. Bosses stay on Bosses.",
};

function keyOf(skill: Skill) {
  return skill.name.toLowerCase().replace(/[^a-z]/g, "");
}

export function skillGuides(): SkillGuide[] {
  return SKILLS.map((skill) => {
    const key = keyOf(skill);
    const osrs = skill.editions.includes("OSRS");
    const note = osrs ? OSRS_NOTE[key] : RS3_NOTE[key];
    const page = note?.page ?? skill.name;
    const wiki = osrs ? osrsWiki(page) : rs3Wiki(page);
    const trainPage = note?.train ?? (osrs ? `Pay-to-play_${page}_training` : `${page}_training`);
    const train = osrs ? osrsWiki(trainPage) : rs3Wiki(trainPage);
    const hooks = osrs ? OSRS_HOOK : RS3_HOOK;
    return {
      skill,
      slug: skill.id,
      hook: hooks[key] ?? "The live page owns the hour.",
      afk: note?.afk ?? "Quiet on this ditch. Confirm the live wiki.",
      fast: note?.fast ?? "The live training page owns the hour.",
      watch: note?.watch ?? "Wiki wins on numbers.",
      early: note?.early ?? "Start where the training page starts.",
      mid: note?.mid ?? "The mid sheet is on the wiki.",
      late: note?.late ?? "The late sheet is on the wiki.",
      wear: note?.wear ?? "Wear what the room asked. Confirm the live page.",
      need: note?.need ?? "Confirm unlocks on the live wiki.",
      money: note?.money ?? "Wiki wins on whether the hour pays.",
      wiki,
      train,
    };
  });
}

export const SKILL_GUIDES = skillGuides();

export function skillGuideById(id: string) {
  return SKILL_GUIDES.find((row) => row.slug === id);
}

export function sisterSkill(row: SkillGuide) {
  const other = row.skill.editions[0] === "OSRS" ? "RS3" : "OSRS";
  const name =
    row.skill.name === "Hitpoints" ? "Constitution" : row.skill.name === "Constitution" ? "Hitpoints" : row.skill.name;
  return SKILL_GUIDES.find((item) => item.skill.editions.includes(other) && item.skill.name === name);
}
