import { SKILLS, type Skill } from "./skills";

export type SkillGuide = {
  skill: Skill;
  slug: string;
  hook: string;
  tagline: string;
  afk: string;
  fast: string;
  watch: string;
  early: string;
  mid: string;
  late: string;
  wear: string;
  need: string;
  money: string;
  wiki: string;
  train: string;
  moving?: boolean;
};

type Note = {
  tagline: string;
  need: string;
  money: string;
  early: string;
  mid: string;
  late: string;
  wear: string;
  afk: string;
  fast: string;
  watch: string;
  page: string;
  train?: string;
  wikiPage?: string;
  moving?: boolean;
};

function osrsWiki(page: string) {
  return `https://oldschool.runescape.wiki/w/${page}`;
}
function rs3Wiki(page: string) {
  return `https://runescape.wiki/w/${page}`;
}

const OSRS_NOTE: Record<string, Note> = {
  attack: {
    tagline: "Melee accuracy. Crabs early. Slayer after that.",
    need: "None to start. Dragon scimitar wants Monkey Madness I. Whip wants 70 Slayer and Abyssal demons.",
    money: "Early crabs cost nothing. A whip and slayer gear cost. Slayer loot pays some of it back.",
    early: "1–60 on ammonite crabs or experiments. Keep a cheap scimitar on task.",
    mid: "60–85 on Slayer. Use the best scimitar or hasta you can afford. Do not camp one monster for extra Attack XP if you still need the slayer level.",
    late: "85–99 on Slayer and the slayer monster the wiki ranks. Special attacks and prayer do more than a new scimitar skin.",
    wear: "Slayer helm on task. Strength bonus over fashion. Bring food you will actually eat.",
    afk: "Sand crabs / ammonite crabs. Not 99-speed.",
    fast: "Slayer with cannon where the task allows. Confirm cannon tasks on the wiki.",
    watch: "Buying a whip before you have the slayer level. Training Attack alone when Strength is 20 behind.",
    page: "Attack",
    train: "Pay-to-play_Melee_training",
  },
  strength: {
    tagline: "Melee damage. Train it with Attack on the same task.",
    need: "Same unlocks as Attack.",
    money: "Same as Attack. Strength bonus is the upgrade that lands the hits.",
    early: "1–60 crabs. Controlled or strength-only if Attack is already ahead.",
    mid: "Slayer. Keep Attack and Strength within about 10 levels.",
    late: "Slayer and the same late melee spots as Attack.",
    wear: "Strength bonus. Slayer helm on task.",
    afk: "Crabs.",
    fast: "Slayer + cannon on legal tasks.",
    watch: "99 Strength with 60 Attack. The accuracy check fails first.",
    page: "Strength",
    train: "Pay-to-play_Melee_training",
  },
  defence: {
    tagline: "Melee defence. Wear the armour the monster hits through.",
    need: "Barrows gloves and a fighter torso help. They are not required to click the skill.",
    money: "Armour is the cost. Defence XP is mostly free on Slayer.",
    early: "Same crabs. Defence XP comes on shared combat.",
    mid: "Slayer in rune / barrows / bandos you can afford. Do not sit in bronze to feel more XP.",
    late: "Slayer and raids prep. Defence is the skill that keeps the trip alive.",
    wear: "Best defensive armour you can repair. Slayer helm on task.",
    afk: "Crabs.",
    fast: "Slayer.",
    watch: "Naked crabs for a screenshot. You will die on the next task.",
    page: "Defence",
    train: "Pay-to-play_Melee_training",
  },
  ranged: {
    tagline: "Distance damage. Ammo is the cost. Chin only your own world.",
    need: "Bone crossbow / MSBI early. Blowpipe wants Zulrah. Bow of faerdhinen wants Gauntlet.",
    money: "Ammo and scales are the tax. Chinning is a cash method, not a free one.",
    early: "1–45 cows, ranged guild, or slayer. Cheap knives or a bone crossbow.",
    mid: "45–75 slayer with MSBI or a crossbow you can afford. Cannon on tasks that allow it.",
    late: "75–99 chinchompas at the maniacal monkeys or skeletal monkeys if you paid for the chins. Blowpipe on slayer if scales are funded.",
    wear: "Ava’s device. Blessed d’hide. Slayer helm on task. Necklace of anguish if you own it.",
    afk: "Crabs with a cheap bow. Slow.",
    fast: "Chinning. Confirm the live wiki for the current spot and prayer.",
    watch: "Chinning a crowded world. Buying a blowpipe with no scale budget.",
    page: "Ranged",
    train: "Pay-to-play_Ranged_training",
  },
  prayer: {
    tagline: "Bones on a gilded or chaos altar. Protect inventory.",
    need: "Priest in Peril for the temple. Restless Ghost helps. Gilded altar is a player-owned house. Chaos altar is in the Wilderness.",
    money: "Dragon bones and superior dragon bones cost. Ensouled heads can be cheaper. Chaos altar saves bones and can take your bag.",
    early: "1–43 quests and cheap bones on any altar.",
    mid: "43–70 dragon bones on a gilded altar with two burners.",
    late: "70–99 superior dragon bones or the bone the wiki ranks this month. Chaos altar if you accept the PKer.",
    wear: "Nothing fancy on a gilded altar. Wilderness: cheap gear, loot keys if you use them, do not bring the bank.",
    afk: "Not afk. Click bones.",
    fast: "Chaos altar or gilded with a runner. Wiki for the current gp/XP.",
    watch: "Chaos altar with a full bank tab. Gilded altar with burners out.",
    page: "Prayer",
  },
  magic: {
    tagline: "Burst and barrage for XP. Auto-cast is not the grind.",
    need: "Desert Treasure for Ancients. Ice Burst 70. Ice Barrage 94. Runes are the cost.",
    money: "Bursting and barraging cost runes. Splashing is dead as a real method.",
    early: "1–55 quests, wind/water blast on slayer, or alchemy if you already have the items.",
    mid: "55–70 slayer casts. 70–94 Ice Burst on dust devils / ancients slayer or the monkey spot if you paid for it.",
    late: "Ice Barrage on the same spots. Thralls if you unlocked Arceuus and they fit the task.",
    wear: "Void or ahrim / ancestral you can afford. Occult necklace. Slayer helm on task.",
    afk: "Alching is the only real afk. It is not 99-speed.",
    fast: "Barrage. Confirm runes and the current cannon/burst spot on the wiki.",
    watch: "Bursting with no prayer and no food. Buying ancestral before 94.",
    page: "Magic",
    train: "Pay-to-play_Magic_training",
  },
  runecraft: {
    tagline: "Essence and pouches to the altar. Guardians of the Rift if you want a minigame.",
    need: "Rune Mysteries. Lost City for cosmic. Hero’s Quest for death. Mourning’s End Part II for death/blood access as designed. Pouches from the Abyss.",
    money: "Lava runes can pay. Bloods and souls can pay. Guardians of the Rift is XP first.",
    early: "1–23 quests and airs. Get the small pouch as soon as the Abyss is open.",
    mid: "23–77 lavas with Magic Imbue, or GOTR for a mix of XP and talismans.",
    late: "77+ bloods. 90+ souls. GOTR if you still want the outfit and the calmer click.",
    wear: "Raiments of the Eye if you have them. Abyss cape / slayer ring for the trip. Stamina.",
    afk: "GOTR is closer to a minigame than afk. ZMI is clicky.",
    fast: "Lava runes or the blood/soul method the wiki ranks this month.",
    watch: "Ourania with no pouch. Abyss with no food and a full cash stack.",
    page: "Runecraft",
  },
  construction: {
    tagline: "Planks on a workbench. Mahogany Homes if you want calmer XP.",
    need: "1 Construction to start. Servant and oak larders come mid. Mythical cape space wants Dragon Slayer II.",
    money: "This skill buys XP. Oak and mahogany planks are the bill. Mahogany Homes costs less XP/hour and less cash.",
    early: "1–33 cheap planks and quests. Build the workshop.",
    mid: "33–52 oak larders. 52–74 mahogany tables or Homes contracts.",
    late: "74–99 mahogany or teak homes, or the bench the wiki ranks. Cape rack / mythics if you own the cape.",
    wear: "Carpenter’s outfit if you have it. Crystal saw. Servant.",
    afk: "Not afk. Homes is slower and kinder.",
    fast: "Mahogany tables / the current bench method. Wiki for gp/XP.",
    watch: "Building without a servant. Buying mahogany at 40 Construction.",
    page: "Construction",
  },
  hitpoints: {
    tagline: "Comes free on Slayer and combat. Food is the only plan.",
    need: "None.",
    money: "Food is the cost. Hitpoints has no separate shop.",
    early: "Train combat. Do not sit on a dummy for Hitpoints.",
    mid: "Train combat. Hitpoints follows the task.",
    late: "Train combat. Do not sit on a dummy for Hitpoints.",
    wear: "Same as the combat style you clicked.",
    afk: "Crabs.",
    fast: "Slayer.",
    watch: "A Hitpoints-only lamp plan with no food budget for the next task.",
    page: "Hitpoints",
    train: "Hitpoints",
  },
  agility: {
    tagline: "Rooftops until 62. Hallowed Sepulchre after that.",
    need: "None to start. Graceful is the outfit. Sepulchre wants 52 for floor 1, 62 for the XP people mean.",
    money: "Marks of grace buy amylase. Sepulchre can pay. The skill itself is time.",
    early: "1–60 rooftops. Canifis at 40. Seers with hard diary.",
    mid: "60–72 rooftops or Sepulchre floor 1–2.",
    late: "72–99 Hallowed Sepulchre. Ardougne rooftop if you want the diary pet chance and a simpler click.",
    wear: "Graceful. Stamina. Hallowed rings / graceful recolour later.",
    afk: "Not afk.",
    fast: "Sepulchre. Confirm floor level on the wiki.",
    watch: "Sepulchre at 52 calling it the 99 method. Brimhaven tickets with no tokens plan.",
    page: "Agility",
  },
  herblore: {
    tagline: "Secondaries first. Mix the potion you will drink or sell.",
    need: "Druidic Ritual. Grim Tales helps. Diary lamps help. Amulet of chemistry is a drop. Mastering Mixology is a minigame — confirm it is still listed on the training page.",
    money: "Secondaries first. Herbs from Farming runs pay this skill. A stack you cannot afford is not a method.",
    early: "1–55 attack, strength, energy potions you will drink. Guam through ranarr. Do not clean herbs as the whole plan.",
    mid: "Prayer potions, super attack, super strength, super restore. Farming Guild contracts pay grimy. Serum and stamina if you will use them.",
    late: "Saradomin brew, forgotten brew, super combat, and the potion the wiki ranks this month. Mixology if that minigame is live.",
    wear: "Amulet of chemistry if you own it. Banked secondaries. Clothes do not matter.",
    afk: "Contracts and grimy you already farm. Cleaning is not training.",
    fast: "The potion the wiki ranks this month.",
    watch: "Buying 99 worth of herbs with no secondaries. Cleaning 10k grimy as the method.",
    page: "Herblore",
  },
  thieving: {
    tagline: "Knights, then elves. Eat on stun. Do not stand in multi if you are marked.",
    need: "None to start. Elves want Mourning’s End and Song of the Elves access. Ardougne diary helps knights.",
    money: "Knights and elves pay. Pyramid Plunder pays sceptres. Pickpocket in the Wilderness and you donate the loot.",
    early: "1–40 men, bakers, warriors. Quest XP if you have it.",
    mid: "40–85 Ardougne knights with the hard diary. Blackjack Bearded Bandits if you know the click.",
    late: "85–99 elves in Prifddinas. Vyres if you unlocked them and the wiki still ranks them.",
    wear: "Rogue’s outfit for double loot. Dodgy necklace. Food.",
    afk: "Not afk. Knights are clicky.",
    fast: "Elves or the current wiki rank.",
    watch: "Elves with no food. Blackjacking on mobile if you cannot hit the stall.",
    page: "Thieving",
  },
  crafting: {
    tagline: "Molten glass, hides, then battlestaves if you bought the orbs.",
    need: "None to start. Giant Seaweed for glass. Lunar Diplomacy for Superglass Make.",
    money: "Glass and hides often cost. Battlestaves can pay. Do not start 99 on dragonhide you cannot sell.",
    early: "1–40 leather, gold, and quests.",
    mid: "40–77 seaweed glass or green/blue d’hide bodies.",
    late: "77–99 battlestaves, redwood / seaweed glass, or the hide the wiki ranks.",
    wear: "Crafting cape later. Glassblowing pipe. Staff of the dead / slayer ring for banked trips.",
    afk: "Cutting gems is slower afk. Not the 99 route.",
    fast: "Superglass Make + blow, or battlestaves.",
    watch: "Buying 20k black d’hide with no buyer. Glass with no seaweed run.",
    page: "Crafting",
  },
  fletching: {
    tagline: "Broad arrows and darts at the bank. Bows if you cut the logs.",
    need: "Broads want slayer points unlocked. Darts want the Smithing/Fletching diary or the dart mould path — confirm on wiki.",
    money: "Broads cost. Stringing yews/magics can pay. Fletching is usually a bank skill.",
    early: "1–52 arrow shafts and shortbows.",
    mid: "52–75 maple / yew longs or broads when unlocked.",
    late: "Broad arrows, dragon/amethyst darts, or magic longs.",
    wear: "None that changes the click. Bank preset.",
    afk: "Stringing bows. Slow.",
    fast: "Darts or broads.",
    watch: "Broads before the slayer unlock. 99 on unstrung bows you will never string.",
    page: "Fletching",
  },
  slayer: {
    tagline: "The task on the board. Skip list lives on the wiki.",
    need: "1 Slayer. Fairytale / desert / fremennik unlocks change the list. Boss tasks want the slayer level and the kill count.",
    money: "This is the paying combat skill if the skip list is correct. Bad tasks burn time.",
    early: "1–50 Turael only if you need points. Mazchna / Vannaka after that.",
    mid: "50–85 Nieve/Steve or Konar if you want the brimstone.",
    late: "85–99 Duradel or Konar. Laniakea is RuneScape — do not put her here.",
    wear: "Slayer helm. Cannon where legal. Protection prayer the monster needs.",
    afk: "Some tasks (nechs, dusts with prayer). Not the whole 99.",
    fast: "Block list + cannon + barrage tasks. Wiki skip table.",
    watch: "Turael boosting at 80 Slayer as the whole plan. Konar every task with no points.",
    page: "Slayer",
  },
  hunter: {
    tagline: "Birdhouse runs on a timer. Chinchompas only on a world you can hold.",
    need: "None to start. Birdhouses want Fossil Island. Red chins want 63. Black chins are Wilderness.",
    money: "Birdhouses pay nests. Chins pay if you keep the world.",
    early: "1–9 quests / crimson swifts. 9–46 birdhouses plus cheap traps.",
    mid: "46–63 falconry or birdhouses. 63 red chins.",
    late: "73+ black chins if you accept Wilderness. Herbiboar at 80 for herblore secondaries.",
    wear: "Camouflage if you have it. Black chins: cheap gear.",
    afk: "Birdhouses are a timer, not a camp. Box traps can be semi-afk.",
    fast: "Black chins or the wiki rank.",
    watch: "Black chins in a full cash stack. Birdhouses with no clock.",
    page: "Hunter",
  },
  mining: {
    tagline: "Motherlode Mine, then amethyst or the rock the wiki ranks.",
    need: "None. Motherlode wants 30. Amethyst wants 92. Tick-manip methods want a quest pickaxe and patience.",
    money: "Motherlode pays nuggets and ores. Amethyst pays. 3-tick granite is XP, not cash.",
    early: "1–30 copper/iron or quests. Get the prospector pieces from MLM.",
    mid: "30–92 Motherlode. Wear the outfit. Pay-dirt is the click.",
    late: "92 amethyst, or granite / stars if you want afk. Mining gloves for amethyst.",
    wear: "Prospector. Expert mining gloves. Celestial ring if you own it.",
    afk: "Stars and amethyst. MLM is light click.",
    fast: "3-tick granite. Only if you will actually tick.",
    watch: "Powermining iron at 70 as the 99 plan. Amethyst with no gloves.",
    page: "Mining",
  },
  smithing: {
    tagline: "Giants’ Foundry or Blast Furnace. Coal bag before the grind.",
    need: "Blast Furnace wants The Giant Dwarf for easy access. Giants’ Foundry wants Sleeping Giants. Coal bag from MLM.",
    money: "Foundry and Blast Furnace can pay. Platebodies at a normal furnace usually do not.",
    early: "1–30 quests and bronze/iron. Get to Foundry / BF as soon as you can.",
    mid: "30–70 Blast Furnace steel/mithril or Foundry.",
    late: "70–99 addy/rune at Blast Furnace, or Foundry swords the wiki ranks.",
    wear: "Smiths’ outfit. Ice gloves at BF. Coal bag. Goldsmith gauntlets do not help smithing.",
    afk: "Foundry is a minigame. BF is clicky.",
    fast: "The bar the wiki ranks at your level.",
    watch: "Smithing rune platebodies on a normal furnace. BF without a coal bag.",
    page: "Smithing",
  },
  fishing: {
    tagline: "Barbarian fishing or the crate. Cook what you keep.",
    need: "Barbarian Fishing wants 48 Fishing, 15 Agility, 15 Strength and Otto’s scene. Infernal eel / minnows have their own levels.",
    money: "Anglerfish and sharks can pay. Barbarian fishing is XP and strength/agility crumbs.",
    early: "1–58 quests, fly fishing, lobster.",
    mid: "58–82 barbarian fishing. Wear the angler’s outfit from Temple Trawler.",
    late: "82–99 minnows, anglers, or infernal eels. 2-tick harpoon if you will tick.",
    wear: "Angler’s outfit. Dragon harpoon. Fish barrel if you own it.",
    afk: "Lobsters, monks, sharks at a bank chest. Slow.",
    fast: "Barbarian or the tick method on the wiki.",
    watch: "99 on lobsters. Minnows with no food and a crowded tile.",
    page: "Fishing",
  },
  cooking: {
    tagline: "Hosidius range so it does not burn. Wines if you bought the grapes.",
    need: "Hosidius kitchen for the 5% burn reduction. Cooking gauntlets from Family Crest.",
    money: "Fish you caught can pay. Wines and 1-tick karambwan are XP methods with a bill.",
    early: "1–35 quests and cheap fish.",
    mid: "35–77 Hosidius fly fish / swordfish / monkfish.",
    late: "77–99 sharks, anglerfish, wines, or karambwan. Wiki for the current gp/XP.",
    wear: "Cooking gauntlets. Chef’s hat does nothing that matters.",
    afk: "Hosidius range is light click.",
    fast: "1-tick karambwan. Only if you will tick.",
    watch: "Cooking sharks on a Lumbridge range. Wines with no jug stack.",
    page: "Cooking",
  },
  firemaking: {
    tagline: "Wintertodt. Warmth is the whole mechanic.",
    need: "50 Firemaking for a real Wintertodt session. Warm clothing. Axe.",
    money: "Wintertodt pays crates. Burning yews at a fire is XP you buy.",
    early: "1–50 any logs. Get to Wintertodt.",
    mid: "50–85 Wintertodt. Warmth is the mechanic.",
    late: "50–99 Wintertodt. Do not leave at 85 unless you hate the minigame.",
    wear: "Warm items. Warmth ring if you own it. Axe. Tinderbox only if you insist on lighting your own.",
    afk: "Wintertodt is a minigame. Not afk.",
    fast: "Wintertodt with the current crate method on the wiki.",
    watch: "Wintertodt in robes. Burning magics on a GE fire for 99.",
    page: "Firemaking",
    train: "Wintertodt",
    wikiPage: "Wintertodt",
  },
  woodcutting: {
    tagline: "The tree you can camp. Forestry is extra XP on the same tile.",
    need: "None. Forestry events want a world with other cutters. Redwood wants 90.",
    money: "Yews and magics can pay. Redwoods are XP. Bird nests are extra.",
    early: "1–60 oaks, willows, teaks.",
    mid: "60–90 yews, maples, Sulliusceps if you unlocked Fossil Island.",
    late: "90 redwoods. Forestry on the tree you already cut.",
    wear: "Lumberjack / forestry outfit. Dragon axe. Felling axe if the event wants it.",
    afk: "Redwoods and yews.",
    fast: "Teaks or the forestry tile the wiki ranks.",
    watch: "99 on normal trees. Forestry with no axe spec.",
    page: "Woodcutting",
  },
  farming: {
    tagline: "Compost from seed. Tree and herb runs while you walk.",
    need: "None to start. Ghosts Ahoy / other diaries help patches. Farming Guild wants 45.",
    money: "This skill pays if you run trees and herbs. Tithe is XP, not cash.",
    early: "1–15 quests and hops. Ultracompost from the start.",
    mid: "15–65 herb runs plus fruit trees when you can afford the saplings.",
    late: "65–99 tree + fruit + hardwood + herb on a timer. Tithe if you want a camp.",
    wear: "Farming outfit. Magic secateurs. Bottomless bucket. Attas / iasor / krasia in the anima patch.",
    afk: "The run is a timer. Tithe is a camp.",
    fast: "Tithe Farm. Confirm on the wiki.",
    watch: "Farming without compost. Buying 99 on dragonfruit with no patch order.",
    page: "Farming",
  },
  sailing: {
    tagline: "Start at Pandemonium. Confirm the live training page before you buy supplies.",
    need: "The Sailing tutorial / Pandemonium unlock. Everything after that is still moving — do not hard-code a 99 route here.",
    money: "Do not buy a full bank of materials until the live wiki says that method still exists.",
    early: "Tutorial and the first tasks on Pandemonium.",
    mid: "The facility and voyage the official training page lists at your level.",
    late: "Same rule. Rebuild this section when Jagex locks the method list.",
    wear: "What the live page lists. Do not copy a YouTube kit from launch week.",
    afk: "Unknown — check wiki.",
    fast: "Unknown — check wiki.",
    watch: "Treating a launch-week blog as the 99 plan.",
    page: "Sailing",
    train: "Sailing_training",
    wikiPage: "Sailing_training",
    moving: true,
  },
};

const RS3_NOTE: Record<string, Note> = {
  attack: {
    tagline: "Revolution bar. Hit the monster’s weakness. Slayer carries levels.",
    need: "None. Tiers follow weapon level. Abilities unlock on the combat interface.",
    money: "Combat gear costs. Slayer and PvM pay it back. Do not buy a new bow to train Attack.",
    early: "Revolution on cows / slayer. One melee bar. Weakness combat.",
    mid: "Slayer with a decent scimitar / spear / halberd for the task.",
    late: "Slayer and the combat dummy only for a small leftover. Bosses belong on Bosses.",
    wear: "Slayer helm on task. Weakness weapon. Revolution ++ when you own it.",
    afk: "Some slayer creatures in an AFK spot. Not every task.",
    fast: "Slayer on a weakness that dies fast.",
    watch: "Manual full-manual on a 40 Attack account. Training Attack with a staff.",
    page: "Attack",
  },
  strength: {
    tagline: "Same tasks as Attack. Damage, not a second camp.",
    need: "None. Same unlocks as Attack.",
    money: "Same as Attack. Strength is the damage stat on the same tasks.",
    early: "Revolution on the same creatures as Attack. One melee bar.",
    mid: "Slayer with Attack. Keep the two stats close.",
    late: "Slayer. Bosses belong on Bosses.",
    wear: "Slayer helm on task. Weakness weapon. Strength bonus.",
    afk: "Some slayer creatures in an AFK spot.",
    fast: "Slayer on a weakness that dies fast.",
    watch: "Training Strength with a staff. A second camp just for this number.",
    page: "Strength",
  },
  defence: {
    tagline: "Armour tier and Death cost. Tank the boss page, not this one.",
    need: "None. Defence armour follows the smithing/combat tier.",
    money: "Repair and Death costs are the bill.",
    early: "Train with Attack and Strength. Do not camp Defence on a dummy for 99.",
    mid: "Train with Attack and Strength. Wear armour you can repair.",
    late: "Train with Attack and Strength. Boss tanking belongs on Bosses.",
    wear: "Best tank armour you can repair.",
    afk: "Same AFK slayer as Attack.",
    fast: "Slayer.",
    watch: "Going to a boss in hybrid fashion with 60 Defence.",
    page: "Defence",
  },
  ranged: {
    tagline: "Bow tier and ammo. Chinchompas only if you own the tile.",
    need: "Weapon tiers. Chins are a method, not a starter kit.",
    money: "Ammo and chins cost.",
    early: "Cheap bows on slayer.",
    mid: "Crystal / ascension path only if funded.",
    late: "Chins at the spot the wiki still lists, or slayer with a real bow.",
    wear: "Ava’s / quiver equivalent on this game. Slayer helm on task.",
    afk: "Some slayer creatures. Slow.",
    fast: "Chins if you own the tile, or slayer with a real bow.",
    watch: "Chins on a public tile you cannot hold.",
    page: "Ranged",
  },
  prayer: {
    tagline: "Bones on an altar. Curses and Soul Split unlock on the prayer list.",
    need: "Temple access. Ancient Curses want The Temple at Senntisten.",
    money: "Frost dragon bones and hydrix if you go that far. Powder of protection / gilded altar math lives on the wiki.",
    early: "Quests and cheap bones.",
    mid: "Dragon / frost bones on a gilded or offering altar.",
    late: "The bone the wiki ranks. Curses on, Soul Split when unlocked.",
    wear: "First age if you own it. Otherwise nothing fancy.",
    afk: "Not afk. Click bones.",
    fast: "The bone the wiki ranks.",
    watch: "Chaos altar logic copied from Old School. Different game.",
    page: "Prayer",
  },
  magic: {
    tagline: "Ability bar, not splash. Bring the spellbook the dungeon wants.",
    need: "Spellbooks from quests. Revolution works here too.",
    money: "Runes cost. Camping abilities on slayer is the normal method.",
    early: "Ability bar on slayer.",
    mid: "The book the task wants — standard, ancient, lunar.",
    late: "Same, with a real staff and a real slayer monster.",
    wear: "Power armour. Slayer helm. Do not splash in 2026 and call it a guide.",
    afk: "Revolution on slayer. Not splash.",
    fast: "Slayer with the spellbook the dungeon wants.",
    watch: "Splashing. Wrong spellbook in a dungeon.",
    page: "Magic",
  },
  runecraft: {
    tagline: "Runespan for calm XP. Abyss for runes you will sell.",
    need: "Rune Mysteries. Abyss miniquest for the abyss.",
    money: "Runespan is XP. Abyss runes can pay.",
    early: "Runespan yellow/grey.",
    mid: "Runespan up the ladder, or abyss for the rune you can craft.",
    late: "Soul / the highest rune you can craft, or Runespan if you want no Pkers.",
    wear: "Infinity / wicked robes if you have them. Essence pouches.",
    afk: "Runespan.",
    fast: "Abyss for runes you will sell, or the rune the wiki ranks.",
    watch: "Copying Old School lava-rune math into RuneScape.",
    page: "Runecrafting",
  },
  construction: {
    tagline: "Planks first. Fort Forinthry frames when the fort is built.",
    need: "Planks and a house. Fort Forinthry wants the fort questline.",
    money: "You buy this XP.",
    early: "Oak / teak in the house.",
    mid: "Mahogany and the servant.",
    late: "Fort frames or the plank the wiki ranks.",
    wear: "Constructor’s outfit. Crystal saw.",
    afk: "Not afk.",
    fast: "Fort frames or the plank the wiki ranks.",
    watch: "Building Fort frames before the fort stands.",
    page: "Construction",
  },
  constitution: {
    tagline: "Same kills as combat. Food and brews are the plan.",
    need: "None.",
    money: "Food.",
    early: "Do not train it alone. Combat XP fills Constitution.",
    mid: "Do not train it alone. Slayer fills Constitution.",
    late: "Do not train it alone. PvM fills Constitution.",
    wear: "Same as the combat style you clicked.",
    afk: "AFK slayer.",
    fast: "Slayer.",
    watch: "A dummy camp for Constitution with no food for the next task.",
    page: "Constitution",
    train: "Constitution",
  },
  agility: {
    tagline: "The course you fail less. Hefin in Prifddinas at late levels.",
    need: "Course levels. Prifddinas wants Plague’s End.",
    money: "Time. Hefin can drop the wings / crystals.",
    early: "Gnome / low courses.",
    mid: "Wilderness course only if you accept the PKer. Barbarian outpost.",
    late: "Hefin. Advanced courses the wiki lists.",
    wear: "Nimble outfit if you have it. Do not wear Graceful — that is Old School.",
    afk: "Silverhawk boots if they are still listed on the wiki. Otherwise not afk.",
    fast: "Hefin or the course the wiki ranks.",
    watch: "Calling rooftops the RuneScape 99.",
    page: "Agility",
  },
  herblore: {
    tagline: "Secondaries first. 120 is a bank sheet, not a secret.",
    need: "Druidic Ritual. Scroll of cleansing helps. Portable wells if they are up. Combination potions and 120 have their own levels.",
    money: "Secondaries first. Super Saradomin brews and combination pots are a bank tab, not a vibe.",
    early: "The potion you will drink. 1–93 the standard ladder on the wiki.",
    mid: "Prayer, super restores, extremes.",
    late: "Overloads, combination potions, 120 content. Portable well + factory outfit if you own them.",
    wear: "Factory / botanist’s. Modified botanist’s mask. Brooch of the Gods if you use portables.",
    afk: "Not afk. Mix potions.",
    fast: "The potion the wiki ranks. Portables if they are up.",
    watch: "Mixing 120 with no secondaries bought. Using an Old School super combat recipe here.",
    page: "Herblore",
  },
  thieving: {
    tagline: "Prifddinas or the safe you can stand. Eat on stun.",
    need: "Plague’s End for Prif. Safecracking has its own level.",
    money: "Prif and safes pay.",
    early: "Men, stalls, knights.",
    mid: "Safecracking when unlocked.",
    late: "Prifddinas clan workers / the method the wiki ranks.",
    wear: "Trahaearn / camo if listed. Food.",
    afk: "Prif clan workers if you can stand the stun.",
    fast: "The method the wiki ranks.",
    watch: "Elves copied from Old School with no Plague’s End.",
    page: "Thieving",
  },
  crafting: {
    tagline: "Jewellery and hide. Portables if they are up.",
    need: "None.",
    money: "Jewellery can pay. Urns and glass depend on price.",
    early: "Gold and leather.",
    mid: "Hides and jewellery.",
    late: "The gem / hide / urn the wiki ranks. Invention will eat junk later — do not trash useful components.",
    wear: "Crafting outfit if you own it. Portable crafter if it is up.",
    afk: "Urns or jewellery at a bank chest.",
    fast: "The gem / hide the wiki ranks. Portables if they are up.",
    watch: "Disassembling the only hide stack you needed.",
    page: "Crafting",
  },
  fletching: {
    tagline: "Broad tips and bows at the bank. Invention eats junk later.",
    need: "Broads from slayer.",
    money: "Bank skill. Check GE before a 120 buy.",
    early: "Shafts and shortbows.",
    mid: "Broad arrows when unlocked.",
    late: "Broad arrows / bakriminel / the bow the wiki ranks.",
    wear: "None that changes the click. Bank preset.",
    afk: "Stringing or broads at the bank.",
    fast: "The bow or tip the wiki ranks.",
    watch: "Disassembling the only stack you needed for 120.",
    page: "Fletching",
  },
  slayer: {
    tagline: "Laniakea when you can use her. Skip list on the wiki.",
    need: "Slayer levels. Laniakea wants 90+ and the island access.",
    money: "This is the paying combat skill if you skip right.",
    early: "Turael only for points.",
    mid: "Duradel / Kuradal.",
    late: "Laniakea. Reaper is bosses — keep it on the Bosses page.",
    wear: "Slayer helm. Weakness weapon. Aggression pots if you use them.",
    afk: "Some tasks with aggression. Not every task.",
    fast: "Skip list + weakness weapon. Wiki skip table.",
    watch: "Putting Duradel on an Old School page or Nieve on a RuneScape page.",
    page: "Slayer",
  },
  hunter: {
    tagline: "Box trap you can leave. Anachronia is a map, not a guess.",
    need: "Anachronia access for the late map.",
    money: "Box traps and big game can pay.",
    early: "Birds and light chins.",
    mid: "Box traps.",
    late: "Anachronia / the wiki rank.",
    wear: "Outfit if you own it.",
    afk: "Box trap you can leave.",
    fast: "The method the wiki ranks.",
    watch: "Old School birdhouse timers pasted here.",
    page: "Hunter",
  },
  mining: {
    tagline: "The Mining & Smithing rework owns the pick. Not Motherlode.",
    need: "Rework tutorial. Pickaxe tiers.",
    money: "Ore is useful. Do not camp Motherlode Mine — it is not this game.",
    early: "Copper to coal on the rework rocks.",
    mid: "Luminite / orichalcite path.",
    late: "Banite / light animica as unlocked. Seren stones if the wiki still lists them.",
    wear: "Magic golem outfit if you have it. The honed perk later.",
    afk: "The rock the wiki still calls afk. Not Motherlode.",
    fast: "The rock the wiki ranks.",
    watch: "Motherlode Mine pasted from Old School.",
    page: "Mining",
  },
  smithing: {
    tagline: "Heat and the rework furnace. Not Blast Furnace.",
    need: "Same rework. Heat is the mechanic.",
    money: "Bars you will use are not a waste. Junk platebodies are.",
    early: "Follow the rework progress bar on bronze and iron.",
    mid: "Follow the rework progress bar. Unfinished items belong in the furnace.",
    late: "Follow the rework progress bar. Unfinished smithing items belong in the furnace, not the GE dump.",
    wear: "Smithing suit. Protean if you already own them — do not buy a new gimmick for this page.",
    afk: "The furnace sit the wiki still lists.",
    fast: "The bar the wiki ranks.",
    watch: "Blast Furnace pasted from Old School.",
    page: "Smithing",
  },
  fishing: {
    tagline: "Swarm or waterfall. Cook what you keep.",
    need: "None.",
    money: "Fish can pay. Swarm is XP.",
    early: "Shrimp to lobster.",
    mid: "Monkfish / swarm.",
    late: "Waterfall fishing in Prif or the swarm the wiki ranks.",
    wear: "Fishing outfit if you own it. Best rod.",
    afk: "Swarm or the waterfall sit.",
    fast: "The fish the wiki ranks.",
    watch: "Barbarian fishing copied from Old School as the RuneScape 99.",
    page: "Fishing",
  },
  cooking: {
    tagline: "The range that does not burn. Portables if they are up.",
    need: "Cooking gauntlets from Family Crest still exist here.",
    money: "Cook what you fish. Portables if live.",
    early: "The food you will eat. Cheap fish.",
    mid: "The food you will eat in PvM.",
    late: "Sailfish / the current high fish on the wiki.",
    wear: "Cooking gauntlets. Portable range if it is up.",
    afk: "The range that does not burn.",
    fast: "The fish the wiki ranks. Portables if they are up.",
    watch: "Hosidius kitchen pasted from Old School.",
    page: "Cooking",
  },
  firemaking: {
    tagline: "A line of logs or a brazier. Not Wintertodt.",
    need: "None.",
    money: "Usually XP you buy.",
    early: "Any logs.",
    mid: "Bonfire line, portable brazier, or the method the wiki ranks.",
    late: "Crystal / magic logs, or the method the wiki ranks.",
    wear: "Firemaking outfit if you own it. No Wintertodt coat.",
    afk: "A bonfire line or brazier.",
    fast: "The log the wiki ranks.",
    watch: "Wintertodt on this page.",
    page: "Firemaking",
  },
  woodcutting: {
    tagline: "The tree you can leave. Crystal and ivy at late levels.",
    need: "Crystal trees want Prif.",
    money: "Ivy is XP. Elder / crystal can pay.",
    early: "Normal to maple.",
    mid: "Yew / magic / ivy.",
    late: "Crystal, elder, or the tree the wiki ranks.",
    wear: "Woodcutting outfit. Best axe.",
    afk: "The tree you can leave. Ivy.",
    fast: "The tree the wiki ranks.",
    watch: "Forestry events pasted from Old School.",
    page: "Woodcutting",
  },
  farming: {
    tagline: "Compost from seed. 120 is tree runs on a sheet.",
    need: "None. Player-owned farm is extra, not the whole skill.",
    money: "Trees and herbs pay. 120 is a calendar.",
    early: "Compost + hops/herbs.",
    mid: "Trees and fruit.",
    late: "120 tree sheet + Manor Farm if you use it.",
    wear: "Farming outfit. Magic secateurs.",
    afk: "Trees grow while you walk. Manor Farm if you use it.",
    fast: "Tree runs on a sheet.",
    watch: "Tithe Farm pasted from Old School.",
    page: "Farming",
  },
  summoning: {
    tagline: "Charms first, then the pouch. The familiar is a tool.",
    need: "Wolf Whistle. Obelisk access.",
    money: "Charms are the gate. Pouches can pay or cost — check GE.",
    early: "Gold charms, low pouches.",
    mid: "Green/crimson.",
    late: "Blue / elder charms and the pouch the wiki ranks.",
    wear: "None that matters more than the charm stack.",
    afk: "Infusing a full inventory at the obelisk.",
    fast: "The pouch the wiki ranks.",
    watch: "Treating the familiar like a pet and never infusing.",
    page: "Summoning",
  },
  dungeoneering: {
    tagline: "Floors. Bind the weapon you will keep using.",
    need: "None. Ring of kinship.",
    money: "Tokens buy useful unlocks. The skill is floors.",
    early: "Solo small floors. Learn bind 1.",
    mid: "Complexity 6. Bind the weapon you actually use on the surface.",
    late: "Large floors / sinkholes if you want tokens. 120 is more floors.",
    wear: "Bind slot is the gear. Do not bring surface gear into Daemonheim.",
    afk: "Not afk. Floors.",
    fast: "The floor size the wiki ranks. Sinkholes if you want tokens.",
    watch: "Rushing floors with no bind and calling it 120.",
    page: "Dungeoneering",
  },
  divination: {
    tagline: "Wisp to crater. Caches on the daily timer.",
    need: "None.",
    money: "Energy can pay. Caches are free daily XP.",
    early: "Pale to gleaming.",
    mid: "Caches every day plus the wisp you can click.",
    late: "Ancestral / incandescent and the crater the wiki ranks. 120 is caches plus that.",
    wear: "Elder divination outfit if you have it.",
    afk: "Wisps at a colony. Caches are a daily.",
    fast: "The colony the wiki ranks plus caches.",
    watch: "Skipping caches for a year then buying a 120 lamp story.",
    page: "Divination",
  },
  invention: {
    tagline: "Disassemble junk. Augment the piece you will keep.",
    need: "80 Smithing, 80 Crafting, 80 Divination. Invention tutorial.",
    money: "Components are the bank. Do not disassemble the weapon you still use.",
    early: "Discover, disassemble cheap junk, level the tool belt.",
    mid: "Augment a weapon you will keep. Siphon, do not instantly disassemble it.",
    late: "120 is research + the item you already use in PvM.",
    wear: "The augmented item. Perks the wiki ranks for that slot.",
    afk: "Siphon the weapon you already swing.",
    fast: "Discoveries plus the item you already use.",
    watch: "Disassembling nox because a blog said components.",
    page: "Invention",
  },
  archaeology: {
    tagline: "Dig, then restore. A damaged artefact is not the finish.",
    need: "Archaeology tutorial. Collectors later.",
    money: "Restored artefacts and materials can pay. 120 is time.",
    early: "Tutorial site. Restore everything.",
    mid: "The next site the skill journal opens.",
    late: "Relics and the site the wiki ranks. 120 is more of that sheet.",
    wear: "Archaeology outfit. Mattock tier.",
    afk: "A hotspot that lasts. Restore at the bench.",
    fast: "The cache and restore loop the wiki ranks.",
    watch: "Banking damaged artefacts forever and never restoring.",
    page: "Archaeology",
  },
  necromancy: {
    tagline: "Rituals and Kili’s tasks. Bosses stay on the Bosses page.",
    need: "Necromancy tutorial. City of Um. Kili for weapon upgrades.",
    money: "Rituals cost materials. Combat pays if you use the style.",
    early: "Tutorial, first rituals, first talent tree picks.",
    mid: "Kili tasks so the weapon actually upgrades. Do not skip her.",
    late: "120 combat + rituals the wiki ranks. Rasial and the rest go on Bosses.",
    wear: "Necromancy armour and the weapon Kili just upgraded.",
    afk: "Combat on undead the wiki names. Rituals are not afk if you must click disturbances.",
    fast: "Rituals the wiki ranks, then Kili.",
    watch: "Calling City of Um a skill guide and leaving Kili out.",
    page: "Necromancy",
  },
};

function keyOf(skill: Skill) {
  return skill.name.toLowerCase().replace(/[^a-z]/g, "");
}

export function skillGuides(): SkillGuide[] {
  return SKILLS.map((skill) => {
    const key = keyOf(skill);
    const osrs = skill.editions.includes("OSRS");
    const note = osrs ? OSRS_NOTE[key] : RS3_NOTE[key];
    const page = note?.page ?? skill.name;
    const wiki = osrs ? osrsWiki(note?.wikiPage ?? page) : rs3Wiki(note?.wikiPage ?? page);
    const trainPage = note?.train ?? (osrs ? `Pay-to-play_${page}_training` : `${page}_training`);
    const train = osrs ? osrsWiki(trainPage) : rs3Wiki(trainPage);
    const tagline = note?.tagline ?? "Confirm the live wiki for the method.";
    return {
      skill,
      slug: skill.id,
      hook: tagline,
      tagline,
      afk: note?.afk ?? "Confirm the live wiki.",
      fast: note?.fast ?? "Confirm the live wiki.",
      watch: note?.watch ?? "Confirm the live wiki.",
      early: note?.early ?? "Start where the training page starts.",
      mid: note?.mid ?? "Confirm the live wiki.",
      late: note?.late ?? "Confirm the live wiki.",
      wear: note?.wear ?? "Wear what the method needs. Confirm the live page.",
      need: note?.need ?? "Confirm unlocks on the live wiki.",
      money: note?.money ?? "Wiki wins on whether the method pays.",
      wiki,
      train,
      moving: note?.moving,
    };
  });
}

export const SKILL_GUIDES = skillGuides();

export function skillGuideById(id: string) {
  return SKILL_GUIDES.find((row) => row.slug === id);
}

export function sisterSkill(row: SkillGuide) {
  const other = row.skill.editions[0] === "OSRS" ? "RS3" : "OSRS";
  const name =
    row.skill.name === "Hitpoints" ? "Constitution" : row.skill.name === "Constitution" ? "Hitpoints" : row.skill.name;
  return SKILL_GUIDES.find((item) => item.skill.editions.includes(other) && item.skill.name === name);
}

const CANON_KEY = "rbs-skills-canon";

export function loadSkillCanon(): "OSRS" | "RS3" {
  try {
    const value = localStorage.getItem(CANON_KEY);
    if (value === "OSRS" || value === "RS3") return value;
  } catch {
    /* private mode */
  }
  return "OSRS";
}

export function saveSkillCanon(canon: "OSRS" | "RS3") {
  try {
    localStorage.setItem(CANON_KEY, canon);
  } catch {
    /* private mode */
  }
}
