/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BriefRouteImport } from './routes/brief'
import { Route as ChronicleRouteImport } from './routes/chronicle'
import { Route as ClassicRouteImport } from './routes/classic'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as EditRouteImport } from './routes/edit'
import { Route as EggRouteImport } from './routes/egg'
import { Route as GuthixLedgerRouteImport } from './routes/guthix-ledger'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as JagexRouteImport } from './routes/jagex'
import { Route as JmodsRouteImport } from './routes/jmods'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as LumbRouteImport } from './routes/lumb'
import { Route as SenntistenRouteImport } from './routes/senntisten'
import { Route as StillRouteImport } from './routes/still'
import { Route as StoryRouteImport } from './routes/story'
import { Route as StreamRouteImport } from './routes/stream'
import { Route as StreamersRouteImport } from './routes/streamers'
import { Route as VarrockRouteImport } from './routes/varrock'
import { Route as YoutubersRouteImport } from './routes/youtubers'
import { Route as BossesIndexRouteImport } from './routes/bosses.index'
import { Route as BossesIdRouteImport } from './routes/bosses.$id'
import { Route as GodsIndexRouteImport } from './routes/gods.index'
import { Route as GodsGodRouteImport } from './routes/gods.$god'
import { Route as MonstersIndexRouteImport } from './routes/monsters.index'
import { Route as MonstersIdRouteImport } from './routes/monsters.$id'
import { Route as TownsIndexRouteImport } from './routes/towns.index'
import { Route as TownsIdRouteImport } from './routes/towns.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefRoute = BriefRouteImport.update({
  id: '/brief',
  path: '/brief',
  getParentRoute: () => rootRouteImport,
} as any)
const ChronicleRoute = ChronicleRouteImport.update({
  id: '/chronicle',
  path: '/chronicle',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassicRoute = ClassicRouteImport.update({
  id: '/classic',
  path: '/classic',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const EditRoute = EditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const EggRoute = EggRouteImport.update({
  id: '/egg',
  path: '/egg',
  getParentRoute: () => rootRouteImport,
} as any)
const GuthixLedgerRoute = GuthixLedgerRouteImport.update({
  id: '/guthix-ledger',
  path: '/guthix-ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const JagexRoute = JagexRouteImport.update({
  id: '/jagex',
  path: '/jagex',
  getParentRoute: () => rootRouteImport,
} as any)
const JmodsRoute = JmodsRouteImport.update({
  id: '/jmods',
  path: '/jmods',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const LumbRoute = LumbRouteImport.update({
  id: '/lumb',
  path: '/lumb',
  getParentRoute: () => rootRouteImport,
} as any)
const SenntistenRoute = SenntistenRouteImport.update({
  id: '/senntisten',
  path: '/senntisten',
  getParentRoute: () => rootRouteImport,
} as any)
const StillRoute = StillRouteImport.update({
  id: '/still',
  path: '/still',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamRoute = StreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamersRoute = StreamersRouteImport.update({
  id: '/streamers',
  path: '/streamers',
  getParentRoute: () => rootRouteImport,
} as any)
const VarrockRoute = VarrockRouteImport.update({
  id: '/varrock',
  path: '/varrock',
  getParentRoute: () => rootRouteImport,
} as any)
const YoutubersRoute = YoutubersRouteImport.update({
  id: '/youtubers',
  path: '/youtubers',
  getParentRoute: () => rootRouteImport,
} as any)
const BossesIndexRoute = BossesIndexRouteImport.update({
  id: '/bosses/',
  path: '/bosses/',
  getParentRoute: () => rootRouteImport,
} as any)
const BossesIdRoute = BossesIdRouteImport.update({
  id: '/bosses/$id',
  path: '/bosses/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GodsIndexRoute = GodsIndexRouteImport.update({
  id: '/gods/',
  path: '/gods/',
  getParentRoute: () => rootRouteImport,
} as any)
const GodsGodRoute = GodsGodRouteImport.update({
  id: '/gods/$god',
  path: '/gods/$god',
  getParentRoute: () => rootRouteImport,
} as any)
const MonstersIndexRoute = MonstersIndexRouteImport.update({
  id: '/monsters/',
  path: '/monsters/',
  getParentRoute: () => rootRouteImport,
} as any)
const MonstersIdRoute = MonstersIdRouteImport.update({
  id: '/monsters/$id',
  path: '/monsters/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TownsIndexRoute = TownsIndexRouteImport.update({
  id: '/towns/',
  path: '/towns/',
  getParentRoute: () => rootRouteImport,
} as any)
const TownsIdRoute = TownsIdRouteImport.update({
  id: '/towns/$id',
  path: '/towns/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brief': typeof BriefRoute
  '/chronicle': typeof ChronicleRoute
  '/classic': typeof ClassicRoute
  '/donate': typeof DonateRoute
  '/edit': typeof EditRoute
  '/egg': typeof EggRoute
  '/guthix-ledger': typeof GuthixLedgerRoute
  '/history': typeof HistoryRoute
  '/jagex': typeof JagexRoute
  '/jmods': typeof JmodsRoute
  '/knowledge': typeof KnowledgeRoute
  '/legal': typeof LegalRoute
  '/lumb': typeof LumbRoute
  '/senntisten': typeof SenntistenRoute
  '/still': typeof StillRoute
  '/story': typeof StoryRoute
  '/stream': typeof StreamRoute
  '/streamers': typeof StreamersRoute
  '/varrock': typeof VarrockRoute
  '/youtubers': typeof YoutubersRoute
  '/bosses/$id': typeof BossesIdRoute
  '/gods/$god': typeof GodsGodRoute
  '/monsters/$id': typeof MonstersIdRoute
  '/towns/$id': typeof TownsIdRoute
  '/bosses/': typeof BossesIndexRoute
  '/gods/': typeof GodsIndexRoute
  '/monsters/': typeof MonstersIndexRoute
  '/towns/': typeof TownsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brief': typeof BriefRoute
  '/chronicle': typeof ChronicleRoute
  '/classic': typeof ClassicRoute
  '/donate': typeof DonateRoute
  '/edit': typeof EditRoute
  '/egg': typeof EggRoute
  '/guthix-ledger': typeof GuthixLedgerRoute
  '/history': typeof HistoryRoute
  '/jagex': typeof JagexRoute
  '/jmods': typeof JmodsRoute
  '/knowledge': typeof KnowledgeRoute
  '/legal': typeof LegalRoute
  '/lumb': typeof LumbRoute
  '/senntisten': typeof SenntistenRoute
  '/still': typeof StillRoute
  '/story': typeof StoryRoute
  '/stream': typeof StreamRoute
  '/streamers': typeof StreamersRoute
  '/varrock': typeof VarrockRoute
  '/youtubers': typeof YoutubersRoute
  '/bosses/$id': typeof BossesIdRoute
  '/gods/$god': typeof GodsGodRoute
  '/monsters/$id': typeof MonstersIdRoute
  '/towns/$id': typeof TownsIdRoute
  '/bosses': typeof BossesIndexRoute
  '/gods': typeof GodsIndexRoute
  '/monsters': typeof MonstersIndexRoute
  '/towns': typeof TownsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brief': typeof BriefRoute
  '/chronicle': typeof ChronicleRoute
  '/classic': typeof ClassicRoute
  '/donate': typeof DonateRoute
  '/edit': typeof EditRoute
  '/egg': typeof EggRoute
  '/guthix-ledger': typeof GuthixLedgerRoute
  '/history': typeof HistoryRoute
  '/jagex': typeof JagexRoute
  '/jmods': typeof JmodsRoute
  '/knowledge': typeof KnowledgeRoute
  '/legal': typeof LegalRoute
  '/lumb': typeof LumbRoute
  '/senntisten': typeof SenntistenRoute
  '/still': typeof StillRoute
  '/story': typeof StoryRoute
  '/stream': typeof StreamRoute
  '/streamers': typeof StreamersRoute
  '/varrock': typeof VarrockRoute
  '/youtubers': typeof YoutubersRoute
  '/bosses/$id': typeof BossesIdRoute
  '/gods/$god': typeof GodsGodRoute
  '/monsters/$id': typeof MonstersIdRoute
  '/towns/$id': typeof TownsIdRoute
  '/bosses/': typeof BossesIndexRoute
  '/gods/': typeof GodsIndexRoute
  '/monsters/': typeof MonstersIndexRoute
  '/towns/': typeof TownsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brief'
    | '/chronicle'
    | '/classic'
    | '/donate'
    | '/edit'
    | '/egg'
    | '/guthix-ledger'
    | '/history'
    | '/jagex'
    | '/jmods'
    | '/knowledge'
    | '/legal'
    | '/lumb'
    | '/senntisten'
    | '/still'
    | '/story'
    | '/stream'
    | '/streamers'
    | '/varrock'
    | '/youtubers'
    | '/bosses/$id'
    | '/gods/$god'
    | '/monsters/$id'
    | '/towns/$id'
    | '/bosses/'
    | '/gods/'
    | '/monsters/'
    | '/towns/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brief'
    | '/chronicle'
    | '/classic'
    | '/donate'
    | '/edit'
    | '/egg'
    | '/guthix-ledger'
    | '/history'
    | '/jagex'
    | '/jmods'
    | '/knowledge'
    | '/legal'
    | '/lumb'
    | '/senntisten'
    | '/still'
    | '/story'
    | '/stream'
    | '/streamers'
    | '/varrock'
    | '/youtubers'
    | '/bosses/$id'
    | '/gods/$god'
    | '/monsters/$id'
    | '/towns/$id'
    | '/bosses'
    | '/gods'
    | '/monsters'
    | '/towns'
  id:
    | '__root__'
    | '/'
    | '/brief'
    | '/chronicle'
    | '/classic'
    | '/donate'
    | '/edit'
    | '/egg'
    | '/guthix-ledger'
    | '/history'
    | '/jagex'
    | '/jmods'
    | '/knowledge'
    | '/legal'
    | '/lumb'
    | '/senntisten'
    | '/still'
    | '/story'
    | '/stream'
    | '/streamers'
    | '/varrock'
    | '/youtubers'
    | '/bosses/$id'
    | '/gods/$god'
    | '/monsters/$id'
    | '/towns/$id'
    | '/bosses/'
    | '/gods/'
    | '/monsters/'
    | '/towns/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BriefRoute: typeof BriefRoute
  ChronicleRoute: typeof ChronicleRoute
  ClassicRoute: typeof ClassicRoute
  DonateRoute: typeof DonateRoute
  EditRoute: typeof EditRoute
  EggRoute: typeof EggRoute
  GuthixLedgerRoute: typeof GuthixLedgerRoute
  HistoryRoute: typeof HistoryRoute
  JagexRoute: typeof JagexRoute
  JmodsRoute: typeof JmodsRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LegalRoute: typeof LegalRoute
  LumbRoute: typeof LumbRoute
  SenntistenRoute: typeof SenntistenRoute
  StillRoute: typeof StillRoute
  StoryRoute: typeof StoryRoute
  StreamRoute: typeof StreamRoute
  StreamersRoute: typeof StreamersRoute
  VarrockRoute: typeof VarrockRoute
  YoutubersRoute: typeof YoutubersRoute
  BossesIdRoute: typeof BossesIdRoute
  GodsGodRoute: typeof GodsGodRoute
  MonstersIdRoute: typeof MonstersIdRoute
  TownsIdRoute: typeof TownsIdRoute
  BossesIndexRoute: typeof BossesIndexRoute
  GodsIndexRoute: typeof GodsIndexRoute
  MonstersIndexRoute: typeof MonstersIndexRoute
  TownsIndexRoute: typeof TownsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brief': {
      id: '/brief'
      path: '/brief'
      fullPath: '/brief'
      preLoaderRoute: typeof BriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chronicle': {
      id: '/chronicle'
      path: '/chronicle'
      fullPath: '/chronicle'
      preLoaderRoute: typeof ChronicleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classic': {
      id: '/classic'
      path: '/classic'
      fullPath: '/classic'
      preLoaderRoute: typeof ClassicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit': {
      id: '/edit'
      path: '/edit'
      fullPath: '/edit'
      preLoaderRoute: typeof EditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/egg': {
      id: '/egg'
      path: '/egg'
      fullPath: '/egg'
      preLoaderRoute: typeof EggRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guthix-ledger': {
      id: '/guthix-ledger'
      path: '/guthix-ledger'
      fullPath: '/guthix-ledger'
      preLoaderRoute: typeof GuthixLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jagex': {
      id: '/jagex'
      path: '/jagex'
      fullPath: '/jagex'
      preLoaderRoute: typeof JagexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jmods': {
      id: '/jmods'
      path: '/jmods'
      fullPath: '/jmods'
      preLoaderRoute: typeof JmodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lumb': {
      id: '/lumb'
      path: '/lumb'
      fullPath: '/lumb'
      preLoaderRoute: typeof LumbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/senntisten': {
      id: '/senntisten'
      path: '/senntisten'
      fullPath: '/senntisten'
      preLoaderRoute: typeof SenntistenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/still': {
      id: '/still'
      path: '/still'
      fullPath: '/still'
      preLoaderRoute: typeof StillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stream': {
      id: '/stream'
      path: '/stream'
      fullPath: '/stream'
      preLoaderRoute: typeof StreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streamers': {
      id: '/streamers'
      path: '/streamers'
      fullPath: '/streamers'
      preLoaderRoute: typeof StreamersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/varrock': {
      id: '/varrock'
      path: '/varrock'
      fullPath: '/varrock'
      preLoaderRoute: typeof VarrockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/youtubers': {
      id: '/youtubers'
      path: '/youtubers'
      fullPath: '/youtubers'
      preLoaderRoute: typeof YoutubersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bosses/': {
      id: '/bosses/'
      path: '/bosses'
      fullPath: '/bosses/'
      preLoaderRoute: typeof BossesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bosses/$id': {
      id: '/bosses/$id'
      path: '/bosses/$id'
      fullPath: '/bosses/$id'
      preLoaderRoute: typeof BossesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gods/': {
      id: '/gods/'
      path: '/gods'
      fullPath: '/gods/'
      preLoaderRoute: typeof GodsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gods/$god': {
      id: '/gods/$god'
      path: '/gods/$god'
      fullPath: '/gods/$god'
      preLoaderRoute: typeof GodsGodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monsters/': {
      id: '/monsters/'
      path: '/monsters'
      fullPath: '/monsters/'
      preLoaderRoute: typeof MonstersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monsters/$id': {
      id: '/monsters/$id'
      path: '/monsters/$id'
      fullPath: '/monsters/$id'
      preLoaderRoute: typeof MonstersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/towns/': {
      id: '/towns/'
      path: '/towns'
      fullPath: '/towns/'
      preLoaderRoute: typeof TownsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/towns/$id': {
      id: '/towns/$id'
      path: '/towns/$id'
      fullPath: '/towns/$id'
      preLoaderRoute: typeof TownsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BriefRoute: BriefRoute,
  ChronicleRoute: ChronicleRoute,
  ClassicRoute: ClassicRoute,
  DonateRoute: DonateRoute,
  EditRoute: EditRoute,
  EggRoute: EggRoute,
  GuthixLedgerRoute: GuthixLedgerRoute,
  HistoryRoute: HistoryRoute,
  JagexRoute: JagexRoute,
  JmodsRoute: JmodsRoute,
  KnowledgeRoute: KnowledgeRoute,
  LegalRoute: LegalRoute,
  LumbRoute: LumbRoute,
  SenntistenRoute: SenntistenRoute,
  StillRoute: StillRoute,
  StoryRoute: StoryRoute,
  StreamRoute: StreamRoute,
  StreamersRoute: StreamersRoute,
  VarrockRoute: VarrockRoute,
  YoutubersRoute: YoutubersRoute,
  BossesIdRoute: BossesIdRoute,
  GodsGodRoute: GodsGodRoute,
  MonstersIdRoute: MonstersIdRoute,
  TownsIdRoute: TownsIdRoute,
  BossesIndexRoute: BossesIndexRoute,
  GodsIndexRoute: GodsIndexRoute,
  MonstersIndexRoute: MonstersIndexRoute,
  TownsIndexRoute: TownsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
